### ISSUE TITLE
malfunction in RTL language

### ISSUE THREAD

**Issue by mmrabbani** [beemdevelopment/Aegis#450] opened 2020-05-31 20:46 UTC
When language is set to system default, and system default language is right to left language (like Arabic), not only UI is broken, but also the code which is generated by app is wrong and is not accepted by services.

![photo_2020-06-01_01-08-50](https://user-images.githubusercontent.com/56675802/83362211-b97a8580-a3a4-11ea-9dd7-8e0716773f2a.jpg)
, but also the code which is generated by app is not valid.

###### Info

* __Version__: 
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ MI A3
* __Android version and ROM:__ lineageos

###### What do you expect to happen?

having RTL UI which generate valid code OR remaining in English when system default is RTL.

**Comment by alexbakker** [comment] 2020-06-01 12:24
Duplicate of #418.

**Closed by alexbakker** 2020-06-01 12:24 UTC
Labels: bug
