### ISSUE TITLE
Camera just show a blank page when open it twice

### ISSUE THREAD

**Issue by muhammadarif1** [beemdevelopment/Aegis#149] opened 2019-06-29 08:16 UTC

**Comment by alexbakker** [comment] 2019-06-29 09:15
We're going to need some more information here:
- Aegis version
- Device model
- Android version
- Steps to reproduce
- Log

**Comment by muhammadarif1** [comment] 2019-06-29 15:50
#### EXPECTED BEHAVIOR 
when I use the camera a second time, the camera should open properly to scan the qr code
#### ACTUAL BEHAVIOR 
when users use the camera for the umpteenth time the camera will only display a blank white page
#### STEP TO REPRODUCE
- install and open the app
-set the pasword 
-then choose to scan the QR code with the camera
-then change the position of the camera from the front camera to the rear camera
-then open the camera again and note the error
- if the error does not appear, open the camera again several times
#### DEVICE AND BROWSER
- PHONE: ANDROID 5.1
- MODEL: OPPO NEO 5
- BROWSER AEGIS: V0.4.3
```[restoreBufCount] get_min_undequeued_buffer_count failed: status[No such device(19)] (restoreBufCount){#184:vendor/mediatek/proprietary/hardware/mtkcam/v1/client/DisplayClient/DisplayClient.cpp}```

**Comment by muhammadarif1** [comment] 2019-07-03 17:20
@beemdevelopment

**Comment by michaelschattgen** [comment] 2019-09-07 09:58
It seems that we can't reproduce this. Does this happen in other apps as well? Maybe even the default camera app on your phone?

**Comment by MorpheusUK** [comment] 2020-02-23 18:09
I am seeing this as well on one of my devices but switching cameras doesn't solve it in my case (It works fine on my Galaxy S10).

I wasn't really expecting support on such an old device running a custom ROM but in case it helps.

Nexus 7 2013
LineageOS 16.0 (5 Feb 2020 security update)
The normal camera app, plus the camera in other apps such as barcode reader work fine.
Aegis v1.1.4

**Comment by alexbakker** [comment] 2020-07-04 09:37
Hopefully fixed by #461.

**Closed by alexbakker** 2020-07-04 09:37 UTC
Labels: bug
