### ISSUE TITLE
QR code scanning with camera or from picture does not work

### ISSUE THREAD

**Issue by Mat-DB** [beemdevelopment/Aegis#1381] opened 2024-05-17 16:24 UTC
### Version

3.0.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung galaxy A20e

### Android version

11

### Steps to reproduce

I am just trying to add an account by scanning a QR code or trying to import a picture and it does not work.
It worked with my camera 2 times after trying and struggling a lot, camera angle, second screen/laptop screen, brightness, light mode/dark mode.

Note: The picture is a screenshot made on my laptop and transferred it to my smartphone.

### What do you expect to happen?

That it scans and recognise the QR code.

### What happens instead?

When using my camera to scan, nothing happens.

When trying to import from the screenshot I get this error message,
```
Screenshot from 2024-05-17.png:
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError: com.google.zxing.NotFoundException
```

EDIT:
My bad, I just notice this is a duplicate of #802

**Comment by alexbakker** [comment] 2024-05-18 10:59
Duplicate of #802.

**Closed by alexbakker** 2024-05-18 10:59 UTC
Labels: bug
