### ISSUE TITLE
Aegis Android : can't manually reorder entries

### ISSUE THREAD

**Issue by x90125** [beemdevelopment/Aegis#1418] opened 2024-07-09 09:12 UTC
Aegis Android  does not permit manually reordering entries (when sorting is set to 'custom').

This would be very useful.

/x13

**Comment by michaelschattgen** [comment] 2024-07-09 09:26
Please stick to our issue template. With such limited information, there's not much we can help you with. What exactly isn't working? Set the order to 'custom' and tap & hold the entries to drag them into a different order.

**Comment by michaelschattgen** [comment] 2024-07-09 09:43
No problem. Ahh right, yeah the custom sorting is disabled whenever there are filters/groups active. This is on purpose since it would make sorting pretty messy and unclear to what you're actually sorting (what would one expect to happen to the sorting if you deactivate the group for example)?

While I agree the user experience is a bit unclear right now, I also currently don't have a better idea on how to improve it. Closing this ticket because this is not a bug, but feel free to continue the conversation.

**Closed by michaelschattgen** 2024-07-09 09:43 UTC
Labels: proposal

**Comment by x90125** [comment] 2024-07-09 09:45
No problem.

Maybe put a message at the bottom when long-clicking an entry that reordering doesn't work in group mode (if it's enabled).

Alvast bedankt kerel. ;)

/x13

**Comment by michaelschattgen** [comment] 2024-07-09 10:14
Yeah perhaps we could show a toast message whenever we think the user tries to reorder while they have a group selection/filter active. Thanks!

<sub>Jij ook! 😉</sub>

**Comment by x90125** [comment] 2024-07-09 10:15
Top!

**Comment by Avrution** [comment] 2025-08-25 18:41
This is still a very silly way to handle things.  There should at least be a way to toggle the group on/off so you can change the order without having to delete all groups.

**Comment by michaelschattgen** [comment] 2025-08-25 19:54
@Avrution I'm confused (once again, i'm sorry) to what you're trying to say. What is stopping you from deselecting all groups in your filter, reorder and toggle your preferred groups again? There is no need to delete all groups.
