### ISSUE TITLE
Android cloud backup doesn't work

### ISSUE THREAD

**Issue by XolbyNax** [beemdevelopment/Aegis#1385] opened 2024-05-20 15:23 UTC
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Xiaomi Mi 10T Pro

### Android version

Android 14

### ROM

Project Elixir 4.2

### Steps to reproduce

Go to:
Settings > Backups
Toggle Android cloud backups

### What do you expect to happen?

I expected to see a popup asking me to log in to my google account, and then to be able to see the backup here:
https://drive.google.com/drive/backups
Like this:
![Screenshot 2024-05-20 180903](https://github.com/beemdevelopment/Aegis/assets/130172696/e790d56a-4a6a-4479-8ac6-9bcb0ae83960)

Pressing Trigger backup doesn't help either, it just makes backups locally.

### What happens instead?

When i enable this option, some red text appears under it. No backups have been made yet. I'd guess this is the issue:
05-20 17:58:47.400  1764  5817 W BackupManagerService: [UserID:0] dataChanged but no participant pkg='com.beemdevelopment.aegis' uid=10527

But I ain't no dev, so, good luck, I guess.

### Log

[logcat.log](https://github.com/beemdevelopment/Aegis/files/15378756/logcat.log)

**Comment by jamfx** [comment] 2024-05-22 14:41
Hi, i have the same issue on my Pixel 7 Pro with Nextcloud as Backuptarget. It is possible, that the issue is longer in the App. my last backup in the Nextcloud is from January 8th 2024. So maybe after that date something changed.
Hopefully this can be fixed. 
Best tegards
JamFX

**Comment by lucasmz-dev** [comment] 2024-05-24 22:15
I don't think this is a bug. This option allows for Aegis to be backed up by Android's internal APIs, (so backup solutions like Seedvault should work) but Aegis does not have integration with G Drive AFAIK. 

WhatsApp (in the screenshot) has its own separation from device backups, if anything, Aegis should have been backed up inside the system's backup. I haven't used Google Play Services but I remember being able to check what was backed up in the last backup someway.

**Comment by jamfx** [comment] 2024-05-28 09:07
Hm, it worked earlier. There is an Option in "Backups" -> Cloud-Backups on Android. Aegis is dropping files in the desired folder. NextCloud seems to "ignore" them or doesn't recognize them. Any suggestions how to trigger this again?

**Comment by alexbakker** [comment] 2024-05-28 18:17
@lucasmz-dev correctly described the way this works.

Enabling the "Android cloud backups" option doesn't immediately trigger a backup. Instead, a notification is sent to Android every time you make a change in Android, hinting that it's time for a backup. Then, whenever Android decides to do a device backup, Aegis will be included.

**Closed by alexbakker** 2024-05-28 18:17 UTC
Labels: bug

**Comment by lucasmz-dev** [comment] 2024-05-28 22:56
@jamfx that's something for you to set up inside Nextcloud, so in their app. (or if you're using FolderSync, or something, then there)
