### ISSUE TITLE
Accrescent?

### ISSUE THREAD

**Issue by Jeffrey2307** [beemdevelopment/Aegis#1518] opened 2024-10-23 16:12 UTC
hey i would love to see the App on Accrescent Store (which is the most secure and private Store and better solution than Github) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

**Comment by alexbakker** [comment] 2024-10-23 16:15
Duplicate of #1271.

**Closed by alexbakker** 2024-10-23 16:15 UTC
Labels: proposal
