### ISSUE TITLE
App unlock via fingerpint doesn't work if phone is unlocked via fingerprint

### ISSUE THREAD

**Issue by mconstabel** [beemdevelopment/Aegis#70] opened 2019-04-24 08:34 UTC
Hello,

if the app is active (in front) and the phone is locked and then unlocked via fingerprint, the app doesn't can be unlocked with fingerprint. I must reopen the app to use fingerprint.

If I unlock the phone via face or pin, fingerprint to unlock app works.

All switched in settings -> security are on.

OnePlus 6, Android 9, OxygenOS 9.0.2

Aegis 0.3.3

**Comment by michaelschattgen** [comment] 2019-04-24 09:12
Thanks for bringing this to our attention!

I just tested this on my own device (Pixel 2XL) and I can't seem to reproduce this, even with all the settings preference switched on. Are there any errors when you try to scan your fingerprint?

**Comment by mconstabel** [comment] 2019-04-24 10:09
I tried more.
I use the phone with a pin, face unlock and fingerprint set up.

If I have the App open, press the power button to lock the phone. Then press the power button to get the Lock-Screen on (I don't lock into the cam, because of face unlock). Touch the fingerprint sensor. Phone is unlocked, app says "touch the sensor" and then "recognized".
This works.

Now: have the App open, press the Power Button to lock the phone. Wait a moment. Then don't press the power button (or something else to get the lock screen on), only use the fingerprint sensor while the screen is off to unlock the phone. The phone is unlocked and the app says "touch the sensor". But the app doesn't react on the sensor any more. No errors. I can use the pin to unlock the app.

**Comment by alexbakker** [comment] 2019-05-01 18:43
We received a bug report from another user who encountered a similar issue:

> I've only had one minor issue, and that is its cooperation with lastpass. Lastpass pops up to input the password, but I just want to use the fingerprint method. Upon closing the lastpass pop-up, it won't take my fingerprint. I'm certain that I can stop lastpass from popping up for this specific app, but I don't understand why this app stops accepting fingerprints after it does.

**Comment by michaelschattgen** [comment] 2019-09-05 13:55
I just found out that fingerprint unlocking also doesn't work on the LG v30. The problem here is that we can't seem to reproduce this and we both (@alexbakker and I) don't have any of these devices. We are happy to accept any pull requests fixing this issue from developers who can reproduce this. 

We will have to wait for now.

**Comment by user8446** [comment] 2019-10-07 18:19
I couldn't reproduce this on a Moto G5 Plus running 8.1

**Comment by alexbakker** [comment] 2019-12-24 13:21
Fixed by #240.

**Closed by alexbakker** 2019-12-24 13:21 UTC
Labels: bug
