### ISSUE TITLE
Aegis in-app NTP clock as alternative to system's for TOTP codes

### ISSUE THREAD

**Issue by ner00** [beemdevelopment/Aegis#851] opened 2021-11-19 23:14 UTC
Sometimes my phone is 5+ seconds behind the atomic clock used by most devices, I guess I should yell at my service provider instead but since Google Authenticator boasts of such functionality, I guess Aegis might as well have something similar since it might be handy to some folks waking up from cryosleep.

The app could have a non-default setting that would allow for an in-app NTP server derived time to be used instead of the system's.

Setting the time manually or restarting the phone sometimes makes the offset shorter, like -1000ms instead of -5000ms. To me 5 seconds is a lot, enough to miss a few TOTP synchronized codes. Of course, this isn't high priority and your app is tons more functional than Google's.

Thanks in advance for considering this.

**Comment by alexbakker** [comment] 2021-11-20 13:40
Duplicate of #785.

**Closed by alexbakker** 2021-11-20 13:40 UTC
Labels: proposal
