### ISSUE TITLE
Improve UI feedback for near rotating entries

### ISSUE THREAD

**Issue by claudioweiler** [beemdevelopment/Aegis#999] opened 2022-10-06 21:46 UTC
Improve UI feedback for near rotating entries.

Current UI feedback is a progress bar at the top. It is always red.

Suggestion is to make OTP codes font as red when it comes near rotating (maybe 5 seconds?). And, also, progress bar can be another color and change to red when it's almost ending.

**Comment by alexbakker** [comment] 2022-10-08 09:49
Duplicate of #411

**Closed by alexbakker** 2022-10-08 09:49 UTC
Labels: proposal
