### ISSUE TITLE
Crash without more info when trying to enable biometric unlock

### ISSUE THREAD

**Issue by ogghi** [beemdevelopment/Aegis#364] opened 2020-04-17 20:40 UTC
Hi there, as the title states.
I just installed latest version from F-Droid, when I try to enable biometric unlock, it crashs with any additional information.

How can I debug?

Blackview BV9800 Pro rooted, Android 9.0

Thanks
ogghi

**Comment by alexbakker** [comment] 2020-04-18 08:58
Could you obtain a log with ADB and share it here? Here's a guide for how to do so: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb.

**Comment by ogghi** [comment] 2020-04-18 19:42
Hi alexbakker, I was not able to save the debug log, got a weird error from adb...nevertheless I got the output to my terminal, so here is where the crash starts:

`04-18 21:40:15.281 12305 12305 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-18 21:40:15.286 12305 12305 E AndroidRuntime: FATAL EXCEPTION: main
04-18 21:40:15.286 12305 12305 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 12305
04-18 21:40:15.286 12305 12305 E AndroidRuntime: java.security.ProviderException: Keystore operation failed
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:324)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:63)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at com.beemdevelopment.aegis.helpers.BiometricSlotInitializer.authenticate(BiometricSlotInitializer.java:63)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at com.beemdevelopment.aegis.ui.PreferencesFragment$10.onPreferenceChange(PreferencesFragment.java:311)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.Preference.callChangeListener(Preference.java:1118)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1182)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1166)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at androidx.preference.Preference$1.onClick(Preference.java:181)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.view.View.performClick(View.java:6611)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6584)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.view.View.access$3100(View.java:783)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26238)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: Caused by: android.security.KeyStoreException: User authentication required
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: 	... 22 more
`

I hope it can be any useful?

**Comment by alexbakker** [comment] 2020-04-27 08:49
Can you take a look at https://github.com/Kunzisoft/KeePassDX/issues/488#issuecomment-600575277? Are you doing something similar?

**Comment by ogghi** [comment] 2020-04-27 08:55
Hi @alexbakker I don't have any Xposed installed. But I think the Blackview ROM is actually not asking for a password even at first boot!
Could this be the problem?

**Comment by alexbakker** [comment] 2020-04-27 09:46
It might be. Do you have a PIN, password or pattern configured for you lock screen?

**Comment by ogghi** [comment] 2020-04-27 09:47
Hi, PIN is configured on my screen.

**Comment by alexbakker** [comment] 2020-04-30 11:11
Here's the exception you got in a bit more readable format:

```
04-18 21:40:15.281 12305 12305 D AndroidRuntime: Shutting down VM --------- beginning of crash
04-18 21:40:15.286 12305 12305 E AndroidRuntime: FATAL EXCEPTION: main
04-18 21:40:15.286 12305 12305 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 12305
04-18 21:40:15.286 12305 12305 E AndroidRuntime: java.security.ProviderException: Keystore operation failed
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:324)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at com.beemdevelopment.aegis.crypto.KeyStoreHandle.generateKey(KeyStoreHandle.java:63)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at com.beemdevelopment.aegis.helpers.BiometricSlotInitializer.authenticate(BiometricSlotInitializer.java:63)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at com.beemdevelopment.aegis.ui.PreferencesFragment$10.onPreferenceChange(PreferencesFragment.java:311)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.Preference.callChangeListener(Preference.java:1118)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.Preference.performClick(Preference.java:1182)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.Preference.performClick(Preference.java:1166)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.SwitchPreferenceCompat.performClick(SwitchPreferenceCompat.java:193)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at androidx.preference.Preference$1.onClick(Preference.java:181)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.view.View.performClick(View.java:6611)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.view.View.performClickInternal(View.java:6584)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.view.View.access$3100(View.java:783)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.view.View$PerformClick.run(View.java:26238)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6702)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: Caused by: android.security.KeyStoreException: User authentication required
04-18 21:40:15.286 12305 12305 E AndroidRuntime: at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
04-18 21:40:15.286 12305 12305 E AndroidRuntime: ... 22 more
```

I suspect this is yet another device-specific bug. It doesn't make sense that ``android.security.KeyStoreException: User authentication required`` is thrown when generating the key. Googling around a bit, it seems that some users are able to fix this by reconfiguring the lock screen in Android settings.

**Comment by ogghi** [comment] 2020-04-30 11:59
I can try and reconfigure it at some point. But it's not that urgent after all!

**Comment by alexbakker** [comment] 2020-04-30 12:11
Alright! I'm going to close this for now, as it seems to be a device-specific issue. Let us know if you ever end up reconfiguring screen lock and whether that fixes it for you.

**Closed by alexbakker** 2020-04-30 12:11 UTC

**Comment by Screwtapello** [comment] 2023-03-01 07:16
In case anybody else finds this issue: I had exactly the same problem on stock Android 10, on a Motorola e7. I fixed the problem, but I can no longer reproduce it so I don't know if this the exact solution but:

- my phone is configured so that I can unlock it by pressing the fingerprint sensor on the back, or by drawing a pattern
- I always unlock my phone with the fingerprint sensor
- when I tried to enable biometric unlock, I got an error message from Aegis whose "details" mentioned `android.security.KeyStoreException: User authentication required`
- I locked my phone, then unlocked it again with the pattern
- then I successfully enabled biometric unlock in Aegis

Now Aegis keeps its secret "can use biometric unlock" permission even if I uninstall and reinstall it, so I guess it's fixed.
