### ISSUE TITLE
Prompt for "Company", not just "Name".

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#436] opened 2020-05-24 21:04 UTC
Today I wanted to add an entry for my Linkedin account.

OK, I see
![3499019](https://user-images.githubusercontent.com/1230959/82764831-740a0580-9e44-11ea-8909-7d0ed89e9c47.jpg)

Well, there is an icon of the top half of a **man**, and the word "Name".

Well, certainly it is asking for the name of a **person**.

OK, so I filled in my Linkedin account name, "jid...". But before I could finish, a big "J" in a circle appeared above it.

I knew that when I was finally finished I should be looking at a big "L" in a circle, not "J".
That's because I am smart and have used such apps before. Indeed this app. But that was last month.

Anyway, please, please, please,
1. Remove the person icon. Replace it with a building icon. Or better yet, [institution](https://www.google.com/search?q=institution+icon&tbm=isch).
2. Remove "Name". Replace it with the much better prompt "Company".

Thank you.

**Comment by michaelschattgen** [comment] 2020-05-24 21:15
Thanks for your bug report, it looks like you got confused here. The 'Name' does not represent the 'Company' as you call it. It's for the name of your account, just like how you were initially filling it.

> I knew that when I was finally finished I should be looking at a big "L" in a circle, not "J".

The circle with the letter in it just uses the value of 'Name' if 'Issuer' (company) is empty. If you continued entering all the information, the circle would indeed show the "L" of LinkedIn.

This isn't a bug, it's how it's supposed to work. You should enter the name of the company in the issuer field, not in the name field.

Closing this issue as it's not a bug, but feel free to continue the discussion.

**Closed by michaelschattgen** 2020-05-24 21:15 UTC
Labels: bug

**Comment by jidanni** [comment] 2020-05-24 21:59
Well then it should flip them, and say much clearer:

Company Name ____
Your User ID ____

And the user would see the big letter fill in from the start.
