### ISSUE TITLE
App "locking" itself or closing when attempting to change icon of entry if "Automatically lock Aegis when the app is minimized" is enabled

### ISSUE THREAD

**Issue by nelsonquintanilla** [beemdevelopment/Aegis#731] opened 2021-04-25 03:27 UTC
###### Info

* __Version__: 1.4.2
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Huawei Honor 7x
* __Android version and ROM__: 
Android version: 9
EMUI version: 9.1.0
Model: BND-L21
Build Number: 9.1.0.178(C432E5R1P1)

###### Steps to reproduce
-Enter the app
-Unlock de vault
-Long press an entry and click the edit icon
-Click the icon of the entry
-Select either of the options to change the icon (here is where the issue happens)

###### What do you expect to happen?
Be able to change the icon.

###### What happens instead?
The app closes itself when opening another app to select the icon.

Edit: The app appears to crash but in reality, I think it is "locking" itself when opening another app to change the icon of the entry. I had the setting "Automatically lock Aegis when the app is minimized" enabled and that appears to be the cause. Either way, it is still an issue worth noting.

**Comment by alexbakker** [comment] 2021-04-26 10:24
Thanks for the report. I'm not able to reproduce this, but I believe I know what could be causing this. I'll work on a patch and have you test it, if you don't mind.

**Comment by nelsonquintanilla** [comment] 2021-04-26 18:53
Sure thing! Thanks for reaching out. Let me know if I can help with anything.

**Comment by alexbakker** [comment] 2021-05-04 19:39
Can you check if you can still reproduce with the following debug APK: https://alexbakker.me/u/d0wi3sxsd9.apk? It's based on the following patch: https://github.com/alexbakker/Aegis/commit/12e47507d06b2c78cdfb588cefed0edd1d340a61.

**Comment by nelsonquintanilla** [comment] 2021-05-05 04:33
https://user-images.githubusercontent.com/42900917/117097273-646b9000-ad28-11eb-8bf1-ba2f7e1250db.mp4

I am still able to reproduce it (video attached). Personally what I did was temporarily disable "Automatically lock Aegis when the app is minimized" to change the icons, then I enabled it again. I think this may be an edge case for this device as you said. Have anyone else reported this issue?

**Comment by alexbakker** [comment] 2021-05-05 09:37
Hmm, that's a bit strange. Can you retry with https://alexbakker.me/u/re64fss2ic.apk and record a log while you're reproducing the issue with ADB (see [the guide](https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb))? I added some log statements that will hopefully tell us more about what's going on.

We've received a couple of similar reports, but those were fairly vague so we weren't able to act on them.

**Comment by nelsonquintanilla** [comment] 2021-05-07 17:54
[aegis_log.pdf](https://github.com/beemdevelopment/Aegis/files/6443457/aegis_log.pdf)
I tried with the apk you provided me. Let me know if this log is helpful.

**Comment by alexbakker** [comment] 2021-05-08 08:46
That's very helpful, thanks! One last debug APK for you to try: https://alexbakker.me/u/9mnqhb34tl.apk. It's based on ad0088eca6af02bf7a8e494da1e27ab555e51c78. No need to capture a log this time.

**Comment by nelsonquintanilla** [comment] 2021-05-08 19:23
It is fixed! Thank you. Works without problems now.

Just piggybacking on that issue but maybe completely unrelated, when the user has enabled the setting "Automatically lock Aegis when" for the case 3) When the device is locked, what happens now is:

1. User locks the device while the app is open and the vault unlocked.
2. The app closes itself.
3. When the user unlocks the device they have to launch it again in order to unlock the vault. 

However, would not it be better like so:

1. User locks the device while the app is open and the vault unlocked.
2. The app locks itself but it does not closes itself.
3. When the user unlocks the device they are already in the main screen to unlock the vault.

Is there any reason why it is like the former case? Should I go ahead and report another issue for this?

**Comment by alexbakker** [comment] 2021-05-08 19:42
> It is fixed! Thank you. Works without problems now.

Great! Thanks for helping us debug this issue. The fix is included in the latest beta release, so I'll close this.

> Is there any reason why it is like the former case? Should I go ahead and report another issue for this?

Yes, unfortunately there are lots of intricacies here related to Android's activity lifecycle that make this difficult. For example, on recent Android versions it is not possible to launch an activity while the app is in the background. That limitation makes responding to the ``SCREEN_OFF`` event, locking the app and then displaying the unlock screen difficult. There are more of these gotchas, but basically, we ended up going with the nuclear "just close all activities" option.

Previously the app would also disappear from the recent apps list after locking, but someone submitted a change to fix that: #714. If someone sees other ways to improve the way we lock Aegis, we're open to suggestions.

**Closed** 2021-05-08 19:42 UTC
Labels: bug
