### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by bossm8** [beemdevelopment/Aegis#1042] opened 2022-11-27 10:04 UTC
First of all, I really like this authentication app, thanks a lot for implementing and maintaining it!

I know there is the grouping feature in which you can group tokens together, however, it would also be nice to have some possibility to group them inside folders. Meaning when I open the app, I see directories where I can put my tokens in (similar like it is in Bitwarden for logins). Because now I just have tons of them in the main view (unless i search for the correct group). But having folders would just show me some folders there.

**Comment by alexbakker** [comment] 2022-11-28 18:26
Thanks for the kind words, but this is a duplicate of #387. We still want to improve the groups feature at some point, but introducing a directory structure is probably not going to happen.

**Closed by alexbakker** 2022-11-28 18:26 UTC
Labels: proposal
