### ISSUE TITLE
The dynamic code turns red in the last few seconds

### ISSUE THREAD

**Issue by netnr** [beemdevelopment/Aegis#1257] opened 2024-01-10 08:39 UTC
I am using the Android App. I know there is a countdown red bar at the top, but it is not easy to notice. However, when I come into contact with the [Authenticator](https://github.com/Authenticator-Extension/Authenticator), the dynamic code will turn red in the last few seconds. This reminder is very effective.

![image](https://github.com/beemdevelopment/Aegis/assets/10579621/5ee98242-2df5-4578-8c31-7f63032720ad)

![image](https://github.com/beemdevelopment/Aegis/assets/10579621/b1408788-7abd-479e-8b30-8020dcfb4c17)

It is best to customize the configuration of the color change reminder in the last few seconds.

**Comment by alexbakker** [comment] 2024-01-10 08:45
Duplicate of #411

**Closed by alexbakker** 2024-01-10 08:45 UTC
Labels: proposal
