### ISSUE TITLE
(Request) Seriously requesting Aegis Authenticator windows aka desktop version in 2024.

### ISSUE THREAD

**Issue by Varniit-pro-90s** [beemdevelopment/Aegis#1270] opened 2024-02-02 23:45 UTC
(Request) Seriously requesting Aegis Authenticator windows aka desktop version in 2024.

I have and being Aegis Authenticator on mobile for many years, and it has been the most dependent app and most recommended app to anybody around me looking for account protection via 2FA. Not a single fault to begin with (except constant popups to enter password despite setting up biometrics). Today, my phones randomly died. All of my logins are in the app itself. Now I cannot log in into any account on my Windows device without mobile, which obviously dead for a sometime. 

I tried looking for Aegis Authenticator Windows EXE or MSI version and cannot find any. So if Aegis Authenticator team can bring an app for desktop and laptop users, it will be beneficial since there are no open source FOSS 2FA apps for windows. All of us aren't dependent on mobile all the time for logins. Some of us have more personal data stored on Windows than mobiles.

🙏🙏🙏🙏🙏🙏

![chrome_nyVWyjv6Ci](https://github.com/beemdevelopment/Aegis/assets/156216269/526e6f06-d992-4fd7-a63f-64122f0e4645)

**Comment by alexbakker** [comment] 2024-02-03 00:05
Duplicate of #165.

**Closed by alexbakker** 2024-02-03 00:05 UTC
Labels: proposal

**Comment by Varniit-pro-90s** [comment] 2024-02-03 00:11
I wanted it to be planned.

**Comment by polyzen** [comment] 2024-02-03 16:56
Perhaps try one of these to run the Aegis app on your desktop and import your backup:
https://developer.android.com/studio/run/emulator
https://learn.microsoft.com/en-us/windows/android/wsa/

**Comment by Varniit-pro-90s** [comment] 2024-02-03 18:41
> Perhaps try one of these to run the Aegis app on your desktop and import your backup: https://developer.android.com/studio/run/emulator https://learn.microsoft.com/en-us/windows/android/wsa/

Are these android emulators on Windows?

**Comment by MaximilianKohler** [comment] 2024-02-14 05:07
>Are these android emulators on Windows?

Yes. One is Nox https://www.bignox.com. I'm not familiar with them all though.

**Comment by Varniit-pro-90s** [comment] 2024-02-14 17:51
> > Are these android emulators on Windows?
> 
> Yes. One is Nox https://www.bignox.com. I'm not familiar with them all though.

Yes, I have heard of this. But not good things. It has virus kind of thing. Would refrain from this. I tried Bluestacks meanwhile but lack of screen lock doesnt make it work.

**Comment by MaximilianKohler** [comment] 2024-02-14 20:26
There are alternatives listed in #165.

**Comment by Varniit-pro-90s** [comment] 2024-02-15 01:23
> There are alternatives listed in #165.

I will see some of them (never heard of those) and come back some time later.
