### ISSUE TITLE
To support protocol: ms-msa

### ISSUE THREAD

**Issue by DictoDictov** [beemdevelopment/Aegis#1573] opened 2024-12-10 14:49 UTC
Cat not set 2-step verification with Aegis for my Live.com account. It says I need Microsoft Authenticator but I want to use Aegis.

The code is kinda look like:
_**ms-msa://code=M.C523_SN1.2.U.**_[something like UID]_**&uaid=**_[another UID]**_&expires=-351961904_**

**Comment by michaelschattgen** [comment] 2024-12-10 18:18
Duplicate of #1493

**Closed by michaelschattgen** 2024-12-10 18:18 UTC
Labels: proposal

**Comment by DictoDictov** [comment] 2024-12-10 19:39
Here it is yours "the best" authenticator! Fack you, lazy ussholes.
