### ISSUE TITLE
Login fails to open after correct password and sends user back to login page

### ISSUE THREAD

**Issue by Jujubash** [beemdevelopment/Aegis#1398] opened 2024-06-20 20:33 UTC
### Version

3.0.1

### Source

F-Droid

### Vault encryption

Yes

### Device

Pixel 6a

### Android version

Android 14

### ROM

GrapheneOS

### Steps to reproduce

Unlocking not working:
1. Try to login with correct password
2. Press the unlock button
Empty menu problem:
3. Get out of the app
4. re-enter the app

### What do you expect to happen?

Unlock to enter the main menu

### What happens instead?

Either:
- Loads a blank page and then goes back to login
- When you leave the app, it shows the main menu, but empty

### Log

```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240605.024/2024061400:user/release-keys
package: com.beemdevelopment.aegis:65
process: com.beemdevelopment.aegis
processUptime: 21611 + 328 ms
installer: org.fdroid.fdroid

java.lang.OutOfMemoryError: Failed to allocate a 31447760 byte allocation with 3448448 free bytes and 3367KB until OOM, target footprint 268435456, growth limit 268435456
	at com.android.org.conscrypt.OpenSSLAeadCipher.reset(OpenSSLAeadCipher.java:140)
	at com.android.org.conscrypt.OpenSSLAeadCipher.doFinalInternal(OpenSSLAeadCipher.java:377)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2074)
	at androidx.core.os.BundleKt.decrypt(SourceFile:18)
	at com.beemdevelopment.aegis.vault.VaultFileCredentials.decrypt(SourceFile:19)
	at com.beemdevelopment.aegis.vault.VaultFile.getContent(SourceFile:25)
	at com.beemdevelopment.aegis.vault.VaultManager.loadFrom(SourceFile:61)
	at com.beemdevelopment.aegis.ui.AuthActivity.access$200(SourceFile:12)
	at androidx.fragment.app.Fragment$7.onTaskFinished(SourceFile:73)
	at com.beemdevelopment.aegis.ui.tasks.PBKDFTask.onPostExecute(SourceFile:699)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by chukfinley** [comment] 2024-06-21 16:09
I also had a black screen after unlock reboot fixed it

**Comment by Jujubash** [comment] 2024-06-24 16:07
Before posting this bug, I've updated everything and afterwards rebooted my device 3 times. No, it's not about rebooting in my case.

**Comment by alexbakker** [comment] 2024-06-25 19:34
This is probably a duplicate of #1298.

@Jujubash Does https://github.com/beemdevelopment/Aegis/issues/1298#issuecomment-1994359143 seem like a plausible description for you situation?

**Comment by sethforprivacy** [comment] 2024-06-26 15:00
Can confirm I can only get a black screen after successful login, running GrapheneOS on latest Play Store Aegis.

**Comment by Jujubash** [comment] 2024-06-26 17:49
@alexbakker No, as I don't use encrypted backups.

**Comment by alexbakker** [comment] 2024-06-28 11:26
@Jujubash I'm talking about my comment here specifically: https://github.com/beemdevelopment/Aegis/issues/1298#issuecomment-1994359143. This applies to all large vault files. How large is yours?

**Comment by Jujubash** [comment] 2024-06-29 18:02
@alexbakker yes, that could be the case. I've used some pictures for each icon, some of them are probably bigegr than 512 x 512 pixels.

**Comment by austinbutler** [comment] 2024-07-01 01:11
Having this issue, seemingly after the latest Play Store update which was today, and I have 61 entries and the backup is 148KB.

**Comment by alexbakker** [comment] 2024-07-01 07:19
@austinbutler Are you sure this is the same issue? Could you share the stacktrace you're seeing?

**Comment by austinbutler** [comment] 2024-07-02 06:49
I found if I let it sit for long enough it eventually loads. But it's a blank screen for at least 30 seconds.

**Comment by alexbakker** [comment] 2024-07-31 10:35
Duplicate of #1298.

**Closed by alexbakker** 2024-07-31 10:35 UTC
Labels: bug
