### ISSUE TITLE
please add an optional lockscreen unlock step to access the vault

### ISSUE THREAD

**Issue by Lanchon** [beemdevelopment/Aegis#1513] opened 2024-10-08 00:45 UTC
hi,

the app allows fingerprint/biometric access to the vault. this mode is fine for some users, but i don't think this should be generally recommended. OT codes can protect recovery access to email accounts and though them to all of someone's digital life.

many countries legally protect passwords from being forcefully revealed while at the same time deny that protection for biometrics. thus, biometric access to the vault is dangerous. the alternative is to type the complete passphrase each time you need access to the vault. this is extremely inconvenient, as the passphrase has to very long to be cryptographically safe.

of course in devices with hardware-backed keystores, a passphrase can effectively be protected behind a short pin or pattern (as well as biometrics). the important difference is that only pins/patterns are legally protected.

**for this reason, i'd like to request a way to configure the vault to unlock using an android lockscreen step, just as there is one for biometrics.**

(also, i would suggest that when enabling the biometrics option, a short pop up should explain the dangers and suggest the lockscreen option as a safer alternative.)

---

thank you so much for this app!!

**Comment by alexbakker** [comment] 2024-10-08 05:53
Duplicate of #212.

If you'd like to use a PIN to unlock Aegis, you can set one as your password and enable the PIN keyboard in Aegis' settings, and then set a separate password for backups.

**Closed** 2024-10-08 05:53 UTC
Labels: proposal

**Comment by Lanchon** [comment] 2024-10-08 06:38
thanks. sorry i didn't find the other issue; i searched though.

> If you'd like to use a PIN to unlock Aegis, you can set one as your password and enable the PIN keyboard in Aegis' settings, and then set a separate password for backups.

(actually i don't use a pin, i use a pattern.)

if i were to do that, where would the passphrase-derived symmetric key for backups kept? would it be kept in the hardware-backed keystore and protected by the pin?

thanks.
