### ISSUE TITLE
Aegis v0.4.3 - The application suddenly stops when adding images

### ISSUE THREAD

**Issue by ammarraisafti** [beemdevelopment/Aegis#150] opened 2019-06-30 09:24 UTC
# Actual behaviour
Supposedly, when I scan an image, then add an image, this application runs well, and that ability can be done.

# Expected behaviour
This application suddenly stops when I add a picture.  Even though I have tried doing it repeatedly, the same problem still occurs.

# Step to reproduce
- Install and open the application. 

- In the security section, select "Password".

- Enter the password, confirm the password.  Then click to continue.

- Click the plus icon, then select the "Scan image" feature.

- Select the image you want to add.  

- Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 0.4.3

# Recording of the bug
https://youtu.be/SQ6TvuVlMgY

**Comment by alexbakker** [comment] 2019-07-02 19:12
Thanks for the very detailed report! Unfortunately, I'm unable to reproduce the crash you're encountering. Can you capture a log with ADB and share it here?

**Comment by ammarraisafti** [comment] 2019-07-03 13:25
Do you mean logcat below?

<code>FATAL EXCEPTION: main
07-03 19:35:49.664 22470 22470 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 22470
07-03 19:35:49.664 22470 22470 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7, result=-1, data=Intent { dat=content://media/external/images/media/182027 }} to activity {com.beemdevelopment.aegis/com.beemdevelopment.aegis.ui.MainActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/182027 from pid=22470, uid=10218 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4322)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4366)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread.-wrap19(Unknown Source:0)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:164)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6550)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
07-03 19:35:49.664 22470 22470 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/182027 from pid=22470, uid=10218 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:2005)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at com.beemdevelopment.aegis.ui.MainActivity.onScanImageResult(MainActivity.java:274)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at com.beemdevelopment.aegis.ui.MainActivity.onActivityResult(MainActivity.java:183)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.Activity.dispatchActivityResult(Activity.java:7291)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4318)
07-03 19:35:49.664 22470 22470 E AndroidRuntime:     ... 9 more</code>

**Comment by alexbakker** [comment] 2019-07-03 16:59
That's the one! Looks like we forget to ask read permissions for external storage. Will be fixed once #158 is merged.

**Comment by ammarraisafti** [comment] 2019-07-03 17:06
Thank you very much

**Closed** 2019-07-31 22:00 UTC
