### ISSUE TITLE
Black Screen after unlocking Database

### ISSUE THREAD

**Issue by SomaKhaos** [beemdevelopment/Aegis#1342] opened 2024-04-01 21:10 UTC
### Version

3.0.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7

### Android version

Android 14

### Steps to reproduce

I open the app, use my fingerprint to unlock my vault. It takes like 1-2 seconds and then there's just a black screen instead of my vault. i then have to minimzie the app and then maximize again to aegis again, to see my vault

### What do you expect to happen?

Unlock the Vault per fingerprint and showing me my vault.

### What happens instead?

Screen turns black and i have to reopen the app to see my vault

**Comment by michaelschattgen** [comment] 2024-04-01 21:12
Thank you for the report. I've been seeing the same strange behaviour on my Pixel with Android 14 as well. I'm 100% sure it's because of the Android version but I haven't figured out what the cause is yet.

**Comment by alexbakker** [comment] 2024-04-01 21:50
@SomaKhaos Could you share the build number of the Android version that you're running?

**Comment by SomaKhaos** [comment] 2024-04-01 21:59
@alexbakker sure it's AP21.240216.010

**Comment by SomaKhaos** [comment] 2024-04-02 11:05
Update: Updated this morning to build AP21.240305.005. So far everything is working as intented again. Seems like the Problem is the other build.

**Comment by michaelschattgen** [comment] 2024-04-02 11:08
I was just about to report the same. Updated this morning too and haven't been able to reproduce this since. I'm closing this issue for now with the assumption that it was caused by the previously mentioned Android build. Feel free to tell us to re-open this issue whenever you run into this again.

**Comment by okkdev** [comment] 2024-06-20 10:54
Just had it happen to me. Solved by reboot. 

Aegis 3.0.1
Pixel 7
AP2A.240605.024

**Comment by michaelschattgen** [comment] 2024-06-20 11:37
I'm afraid the Google Pixel June update that came out a little over a week ago reintroduced this bug... I'm opening this issue again, although I'm not sure yet whether it's possible to fix this on our end or we'll have to wait for Google to release a fix.

**Comment by Jujubash** [comment] 2024-06-21 08:42
I'm running through this bug and I have the latest app and OS version too:
https://github.com/beemdevelopment/Aegis/issues/1398

**Comment by Jujubash** [comment] 2024-06-24 22:42
Nor Updating, nor rebooting worked.

**Comment by rashidnhm** [comment] 2024-06-25 15:14
Running into this issue now (on Pixel 6a). Is there any workaround for me to see my tokens in the meantime as I'll locked out without having access to the 2fa tokens

**Comment by alexbakker** [comment] 2024-06-25 19:46
A log captured while reproducing the issue would be much appreciated: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb

**Comment by bickman2k** [comment] 2024-06-26 16:01
I was able to find a workaround on my Pixel 6 Pro. When the screen goes black, go back to the home screen, then re-open the app. The tokens are then visible.

**Comment by bickman2k** [comment] 2024-06-26 16:11
Attached debug log file. The steps I performed were to launch the app, immediately begin capturing the Aegis debug log, exited biometric unlock, re-initiating biometric unlock, getting the black screen, waiting, going back to the home screen, then re-opening the app which then showed the tokens.

[debugaegis.log](https://github.com/user-attachments/files/15992029/debugaegis.log)

**Comment by sharpsan** [comment] 2024-06-27 14:06
New to the app, and I have experienced this bug twice within the past 2 weeks.  Pixel 8 Pro June patch.  Restarting my device has worked so far.

**Comment by alexbakker** [comment] 2024-06-28 11:25
@bickman2k Thanks, but we're going to need the full capture without the Aegis filter in order to get enough information. If you're not comfortable sharing the log publicly, feel free to share it with us via email privately.

**Comment by bickman2k** [comment] 2024-06-28 11:30
I can pull another log in a couple of days as I'm camping right now. I can email it when it is pulled.

**Comment by fraction1** [comment] 2024-06-30 05:53
@alexbakker also got the blackscreen when opening Aegis (v3.1) latest update from he playstore.  The previous version had the same issue.

Running lineageos android 14 latest build
Ap2a 240605.025
Los: 21-20240626-NIGHTLY-enchilada
On my oneplus6

When openening Aegis, unlock it with fingerprint, i got a blackscreen (no info visable)
Force close aegis, clear cache doesn't fix it.
 
(Tried to open aegis with passwordphrase also does't work, still got a black screen)

**Comment by garpunkal** [comment] 2024-06-30 11:39
I'm also still receiving this problem

**Comment by idl0r** [comment] 2024-07-01 22:35
Do you guys still need a log or something?

**Comment by michaelschattgen** [comment] 2024-07-01 22:36
Yes please.

**Comment by idl0r** [comment] 2024-07-02 07:40
Just sent one via mail. Let me know if you need anything else.

**Comment by idl0r** [comment] 2024-07-02 21:41
So either the reboot or the just released and installed July update seems to have fixed it for me, at least for now. Can anybody else confirm that?

**Comment by rashidnhm** [comment] 2024-07-02 21:44
I don't have the July update .. but I haven't hit the issue again since the first time.

What I have done differently since the first time is removing usage of fingerprint auth and only using manual password entry.

**Comment by michaelschattgen** [comment] 2024-07-02 21:46
>So either the reboot or the just released and installed July update seems to have fixed it for me, at least for now. Can anybody else confirm that?

There's a **big** chance the July update fixed the issue. I was running an Android 14 beta update back in april which introduced this bug for me, then suddenly a new beta version fixed it again. Hopefully we're going to see more reports about the July update fixing this weird behaviour.

>What I have done differently since the first time is removing usage of fingerprint auth and only using manual password entry.

Yeah I was already expecting the biometrics auth popup causing this issue. Glad you found a workaround!

**Comment by sharpsan** [comment] 2024-07-02 21:55
I was on the June update and it only happened to me twice.

**Comment by fraction1** [comment] 2024-07-03 05:19
Itnseems after rebooting the latest aegis update the problem doesn't accure (3days without a problem) fingers crossed

**Comment by Jujubash** [comment] 2024-07-05 07:49
> I don't have the July update .. but I haven't hit the issue again since the first time.
> 
> What I have done differently since the first time is removing usage of fingerprint auth and only using manual password entry.

same here

**Comment by idl0r** [comment] 2024-07-05 07:50
Still looking good. No more issues since the latest (July 2024) Pixel update

**Comment by Jujubash** [comment] 2024-07-05 07:54
> Still looking good. No more issues since the latest (July 2024) Pixel update

sorry, I meant, I still have the problem. I can make even a video...

**Comment by Jujubash** [comment] 2024-07-05 08:17
@michaelschattgen you are right

**Comment by BastLast** [comment] 2024-07-06 22:15
This has been happenning too on my pixel 8A android 14. Found a work arround of switching to another app (without closing aegis) and coming back and it loads the vault directly. Don't know if that can help x)

**Comment by skibbipl** [comment] 2024-07-09 14:46
I would like also to confirm that updating to July 2024 android patch solved the issue on my Pixel 8 Pro.

**Comment by sharpsan** [comment] 2024-07-11 19:53
This issue popped back up for me, surprisingly.  On the July patch this time.  This appears to still be an ongoing issue.

**Comment by vivident4004** [comment] 2024-07-11 20:35
I updated to Aegis 3.1 and this issue started appearing, and I've never seen this before. I've experienced this issue on a Pixel 8 Pro with GrapheneOS 2024070201 (rebased onto AP2A.240705.005 Android Open Source Project release). But after updating to GrapheneOS 2024070900 the app now seems to be working again normally.
On a Pixel 6a with stock Android 14 and latest patches no issue appeared.
The app on both models was installed and updated with the GitHub release.

**Comment by alexbakker** [comment] 2024-07-14 13:20
I've finally had the (dis)pleasure of encountering this bug on my own device (on the July security update: AP2A.240705.005), so was able to do some more digging. This is a weird one. Almost certainly a bug in Android.

The cause appears to be the fact that we call [``startActivityForResult``](https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)) during [``onResume``](https://developer.android.com/reference/android/app/Activity#onResume()). I was able to reproduce the issue in a new Android project with two activities. The main activity calls ``startActivityForResult`` during ``onResume`` to start the second activity. The second activity has a button that calls ``finish()`` to return to the main activity. Tap the button and boom: Freeze and a black screen shortly afterwards. 

Calling ``startActivityForResult`` during [``onStart``](https://developer.android.com/reference/android/app/Activity#onStart()) instead appears to be a workaround for the issue.

One of the last couple of security updates must have contained a change that broke this.

**Comment by alexbakker** [comment] 2024-07-14 19:06
I've filed an issue: https://issuetracker.google.com/issues/352963108

**Comment by michaelschattgen** [comment] 2024-07-17 21:02
We just created a new beta release (v3.1.1-beta) that includes the workaround implemented in #1430. This release is currently rolling out to our beta users in the Google Play Store. Join the beta program if you want to try the fix yourself or download the APK from [here](https://github.com/beemdevelopment/Aegis/releases/tag/v3.1.1-beta1).

**Comment by uniquePWD** [comment] 2024-07-18 05:18
Just came to report this. Glad to see a fix is rolling out.

**Comment by alexbakker** [comment] 2024-07-31 10:38
It's been a week since the release of v3.1.1 and we haven't received any more reports of this issue, so I think it's safe to say this has been fixed. Thank you all for helping us debug this!

**Closed by alexbakker** 2024-07-31 10:38 UTC
Labels: bug, bug-confirmed

**Comment by julwac** [comment] 2024-07-31 22:49
The issue just reappared for me, I think. Pixel 7, Android 14, July update, App version v3.1.1. As I was trying to unlock with my fingerprint, nothing happened. The unlock screen stayed the same and the vault didn't actually unlock.

Maybe it's just a random stutter. But what is suspicious is that I haven't rebooted the device in a long time now. And just then, this odd behaviour reappears. And as described above not rebooting in a while caused the previous issue.
