### ISSUE TITLE
Unlocking the database takes a long time

### ISSUE THREAD

**Issue by mpeter50** [beemdevelopment/Aegis#1024] opened 2022-11-09 17:13 UTC
### Version

v2.0.3

### Source

F-Droid

### Device

Xiaomi Redmi 3S

### Android version

Android 6

### ROM

MIUI 8

### Steps to reproduce

1. Open app
2. Enter/autofill password
3. Wait until the list of codes appear

### What do you expect to happen?

Unlocking the database takes only a few seconds (5-30)

### What happens instead?

Unlocking the database takes 1 minute 20 seconds

### Log

```
2022-11-09 18:06:30.319 10543-32417/? W/XSpaceManagerService: checkXSpaceControl, from:com.miui.home, to:com.beemdevelopment.aegis, with act:android.intent.action.MAIN, callingUserId:0, toUserId:0
2022-11-09 18:06:30.320 11296-12163/? D/WtComponentManager: start the package is com.beemdevelopment.aegis the call is com.miui.home startType is 1
2022-11-09 18:06:30.323 10543-32417/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.beemdevelopment.aegis/.ui.MainActivity bnds=[216,739][310,833] (has extras)} from uid 10022 on display 0
2022-11-09 18:06:30.372 11296-11394/? D/WtProcessController: packageMoveToBackground packageName:com.beemdevelopment.aegis
2022-11-09 18:06:30.373 11296-11394/? D/WtProcessController: set foreground process size 1 pid:6633pacakgeName:com.beemdevelopment.aegis
2022-11-09 18:06:30.513 11296-11576/? D/WtComponentManager: start the package is com.beemdevelopment.aegis the call is com.beemdevelopment.aegis startType is 1
2022-11-09 18:06:30.515 10543-12002/? I/ActivityManager: START u0 {cmp=com.beemdevelopment.aegis/.ui.AuthActivity (has extras)} from uid 10494 on display 0
2022-11-09 18:06:30.766 10543-10633/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{d3ddd7b u0 com.beemdevelopment.aegis/.ui.AuthActivity t54560} time:1004229169
2022-11-09 18:06:30.800 11662-11662/? I/AndroidIME: AbstractIme.onActivate():83 PasswordIme.onActivate() : EditorInfo = Package = com.beemdevelopment.aegis : Type = Password : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Hide : NoPersonalizedLearning = Disable, IncognitoMode = false
2022-11-09 18:06:38.169 11296-11394/? D/WtProcessController: packageMoveToBackground packageName:com.beemdevelopment.aegis
2022-11-09 18:06:38.169 11296-11394/? D/WtProcessController: set foreground process size 1 pid:6633pacakgeName:com.beemdevelopment.aegis
2022-11-09 18:06:38.397 10543-10633/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{d3ddd7b u0 com.beemdevelopment.aegis/.ui.AuthActivity t54560} time:1004236800
2022-11-09 18:07:59.400 10543-10633/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{4707d5a u0 com.beemdevelopment.aegis/.ui.MainActivity t54560} time:1004317803
2022-11-09 18:07:59.439 10543-12030/? D/PerfShielderService: com.beemdevelopment.aegis|com.beemdevelopment.aegis/com.beemdevelopment.aegis.ui.MainActivity|346|1004317697204776|286|0
2022-11-09 18:07:59.445 11806-12621/? D/MiuiPerfServiceClient: interceptAndQueuing:6633|com.beemdevelopment.aegis|346|286|running|null
```

**Comment by mpeter50** [comment] 2022-11-09 18:29
I'm trying to create a useful performance profile, but so far I wasn't able to reproduce the problem with the debug build (based on 32ee0915), by just importing the database of the normal app and setting up the settings the same way.

I started to go a bit further, and I'm copying all data in the app's directory (in `/data/data/<packagename>`) to the debug version's directory. It seems copying the resource files are going really slow.. they are very small, the sum of all app data is 1,1 MB, but the copy goes at the speed of 2 files in a second.

Well, this might not be an Aegis problem, but maybe something deeper.
However I was copying with a file explorer app, not with `cp` in a shell, so hopefully this might have just been it's own overhead, as there are many files in a subdirectory of the icon pack.

**Comment by mpeter50** [comment] 2022-11-17 17:18
I was able to make a performance profile for the app, which I've attached to this comment.
Unfortunately, I was only able to make a sampling profile (with 1 ms rate), as the content of the tracing profile was empty after the first few seconds. Possibly this was because of the size limit, which is by default 8 Mb, but increasing it to 32 Mb (the maximum allowed by android studio) did not help much.

[cpu-art-20221117T181615.zip](https://github.com/beemdevelopment/Aegis/files/10033971/cpu-art-20221117T181615.zip)

**Comment by alexbakker** [comment] 2022-11-17 18:21
Thanks for following up!

As suspected during our previous chat on Matrix, _a lot_ of time is being spent doing key derivation. According to the flame chart, 2.2 minutes is being spent in SMix:

![image](https://user-images.githubusercontent.com/2387841/202522829-e9e88201-52c9-4a0d-bc74-4e9c8e17b3e7.png)
<sub>(Pretty funny how it thinks that this function is located in ``de.psdev.licensesdialog``, probably due to R8 moving things around)</sub>

Inside that function, it spends a total of 10 seconds doing XOR and making memory copies. Then the signal goes dark. What could it be spending the rest of the time on? Memory allocation?

I'm afraid I can't immediately think of a solution for this.

**Comment by mpeter50** [comment] 2022-11-17 18:29
Could it be something the sampling profile didn't catch?
Also, you mentioned memory allocation as an idea. Would it help if I made a memory profile, too?

**Comment by mpeter50** [comment] 2022-11-17 19:11
As I said earlier, I can't capture ~~long~~ not-short tracing profiles, but I tried to do 2 small ones to see if it shows something more.
I did one a split second before pressing the unlock button, and another ~15 seconds later.
They do show more.

Inside 5,3 seconds of BlockMix, Integer.rotateLeft was running 2,36 seconds, and for comparison in this short time arraycopy and Xor has only ran for 63+51 ms.
According to the "Events" tab, this runs for much shorther time than the other 2, but it is called a lot more frequently.

[Aegis.zip](https://github.com/beemdevelopment/Aegis/files/10034765/Aegis.zip)

**Comment by alexbakker** [comment] 2022-11-17 19:34
Seeing something similar here.

Turns out I'm actually able to reliably reproduce this on a different device (but only when running the app with a debugger attached). On that device it takes 30 seconds, not as bad as 2 minutes, but still bad. A CPU profile of that debug build gives some more details that look similar to yours:

![image](https://user-images.githubusercontent.com/2387841/202528944-b9a2b774-531d-4358-bdb5-e6a19863e3b3.png)

As you noticed most of the time is spent in ``rotateLeft``. Here's what that function looks like:

```java
public static int rotateLeft(int i, int distance) {
    return (i << distance) | (i >>> -distance);
}
```

Pure computation, no memory allocation. Something is making everything very slow.

> Also, you mentioned memory allocation as an idea. Would it help if I made a memory profile, too?

I thought so, but it now looks like this is unrelated to memory allocation.

**Comment by alexbakker** [comment] 2022-11-17 20:29
Aha! We're getting somewhere. On a hunch I pulled out BouncyCastle's SCrypt and Salsa20 implementation and replaced the call to their ``Integers.rotateLeft`` wrapper function with Java's ``Integer.rotateLeft`` (the function they're wrapping).

Now unlocking only takes 3 seconds, and the flame graph looks much more reasonable:

![image](https://user-images.githubusercontent.com/2387841/202551337-aebf3b28-cbbb-44c3-915b-bdb1df7a10c0.png)

After this change ``rotateLeft`` no longer appears in the trace at all, suggesting that the JVM decided to inline that function, eliminating the need for a gazillion function calls.

**Comment by mpeter50** [comment] 2022-11-17 21:11
Oh, I totally missed that in `org.bouncycastle.crypto.engines.Salsa20Engine#salsaCore` these are not calls to the original rotateLeft function.

Do you remember how much time did it take for you to unlock while still using the wrapper function?
Also, why did that wrapper function add overhead? Does it count _that_ much when it is called this very frequently?

**Comment by mpeter50** [comment] 2022-11-17 21:14
Also, it's still weird that the debug version I built locally unlocked with the old, faster speed with the same database.
Why didn't this affect that? It even has optimizations disabled.

**Comment by alexbakker** [comment] 2022-11-17 21:49
> Do you remember how much time did it take for you to unlock while still using the wrapper function?

I'm only able to reproduce this with a debugger attached. For me it took ~30 seconds, sometimes more. So going from that to ~3 seconds is at least a 10x performance improvement.

> Also, why did that wrapper function add overhead? Does it count that much when it is called this very frequently?

Yeah, in very tight loops, the overhead of calling a function starts to matter. I suspect that the JVM inlines functions like ``Integer.rotateLeft`` from the standard library by default. Perhaps it inlines less aggressively depending on the environment (for example: debugger attached, certain devices, certain settings, etc), causing wrapper functions like BouncyCastle's ``Integers.rotateLeft`` to not get inlined. This is pure speculation, but it sure seems plausible after seeing these results.

> Also, it's still weird that the debug version I built locally unlocked with the old, faster speed with the same database. Why didn't this affect that? It even has optimizations disabled.

That I can't explain. Nevertheless, our flame graphs look very similar, so I suspect that this will improve performance for you as well.

**Comment by alexbakker** [comment] 2022-11-17 22:08
Anyway, hopefully this weekend I'll have some time to submit a PR with this change to the BouncyCastle guys and we'll see what they think. It'll take a while before that ends up in a release (if ever), so I'm afraid we'll have to keep a copy of their SCrypt and Salsa20 implementation with our fix applied in Aegis' repo for a while.

**Comment by alexbakker** [comment] 2022-11-20 15:35
[v2.1](https://github.com/beemdevelopment/Aegis/releases/tag/v2.1) is out with the potential fix. I see that you're using the F-Droid release, so we'll have to wait a bit before it's available there. But please let us know whether this fixes the issue for you!

**Comment by mpeter50** [comment] 2022-11-24 17:56
Well, this is weird.

After updating to v2.1, unlocking takes only 5 seconds.
Even if not this exact change caused the issue to disappear, it did disappear.

Actually I was thinking about reinstalling the app (I mean, the same v2.0.3 from F-droid that I had until now) to see if it would solve anything, but didn't get to try that actually.

If you think so, the issue can be closed.

**Comment by alexbakker** [comment] 2022-12-03 13:39
I'm going to leave 5dfdbabf30be3ec87c9f72e2da51634c7c50388b in for now, because it doesn't hurt (and actually improves performance while debugging). For this issue though, I don't think there's much more that can be done, so I'll close this.

> Actually I was thinking about reinstalling the app (I mean, the same v2.0.3 from F-droid that I had until now) to see if it would solve anything, but didn't get to try that actually.

That could be interesting. Let me know if you end up trying this and find any interesting results.

**Closed by alexbakker** 2022-12-03 13:39 UTC
Labels: bug
