### ISSUE TITLE
Password error when unlocking vault by password

### ISSUE THREAD

**Issue by ghiki** [beemdevelopment/Aegis#479] opened 2020-06-18 22:33 UTC
###### Info

* __Version__: 1.2
* __Source__: (Google Play/GitHub/F-Droid/?) : Google Play
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No : Yes + Biometric
* __Device:__ : Redmi Note 9S
* __Android version and ROM:__ : Android 10 with MIUI 11 stock (11.0.8.0 Stable)

###### Steps to reproduce
Lock the vault by password and try to unlock entering this password.

###### What do you expect to happen?
Unlock the vault

###### What happens instead?
Wrong password alert (password is correctly entered)

I attach video
https://youtu.be/pSouNGMgOnQ

![Screenshot_2020-06-19-00-29-36-497_com beemdevelopment aegis](https://user-images.githubusercontent.com/854302/85078160-15764400-b1c4-11ea-93d4-e8d644044fff.jpg)

**Comment by ghiki** [comment] 2020-06-18 22:43
As additional comment, with previous 1.1.4 version from F-Droid, the vault unlocks succesfully by password

**Comment by michaelschattgen** [comment] 2020-06-18 23:00
Thanks for your bug report and video. The lockscreen showing up immediately after setting a new password is definitely not normal behaviour and is actually caused by a crash. You're not setting a new password, it's crashing. Judging by the exception I can see in Google Play it is caused by Aegis not being able to find the old password to remove/replace.

When did it start to happen? Did it stop working after the update to 1.2 or did you install Aegis fresh without a vault?

**Comment by ghiki** [comment] 2020-06-18 23:05
I tried importing a vault and also creating a now one, in none of the times the password is recognized when I'm accessing, only is recognized while I'm importing the vault file (see that I have navigation gestures and I go back after setting new password). This happens only after update to 1.2, I tried with previous version and the problem dissapears

**Comment by alexbakker** [comment] 2020-06-19 08:13
This is a strange issue. Are you able to reproduce this with a clean install of Aegis? If so, could you walk us through the full list of steps you take to reproduce it? From start (clean app install) to finish (the crash).

I would advise you to create a temporary plain text export of your vault, just in case.

**Comment by alexbakker** [comment] 2020-06-19 09:22
A follow up question: when did you first start using Aegis? Were you already using Aegis with version 1.1.4? Or did you start with 1.2-beta1 or 1.2-beta2, by any chance?

**Comment by ghiki** [comment] 2020-06-19 10:00
> A follow up question: when did you first start using Aegis? Were you already using Aegis with version 1.1.4? Or did you start with 1.2-beta1 or 1.2-beta2, by any chance?

I have been using for two years or so. It's so strange, after entering BETA in GPlay It works ok..
🤔

**Comment by alexbakker** [comment] 2020-06-19 10:14
It's still not clear to me. Did you ever have a beta version of Aegis installed? (downloading a beta APK from GitHub also counts)

Here's the only way I can come up with that could have gotten your Aegis vault into this state:
- You (re-)configured Aegis during 1.2-beta1 or 1.2-beta2 and selected "None" for security during the onboarding.
- Due to a bug (see: 92b6738ff4185a23d3bd863db87a4d4906840474) Aegis ignored that preference and encrypted the vault anyway.
- While the app was still open after completing the onboarding, you enabled biometrics in settings.
- Now you can only open the app with biometrics.
 
Does that sound plausible?

**Comment by ghiki** [comment] 2020-06-19 10:26
Nope, I never used beta before this issue appears. (The video in the first post was done in 1.2 Stable), but now, with the same Play Store version the issue dissapeared and I can't reproduce. So close the bug if you want and if happens again I'll record the exactly steps I've done. Thank you so much

**Comment by alexbakker** [comment] 2020-06-19 11:36
> The video in the first post was done in 1.2 Stable

Right. My theory was that you used 1.2-beta1 or 1.2-beta2, silently got your vault into a bad state as described and noticed the issue when trying to change the password after upgrading to 1.2.

> if happens again I'll record the exactly steps I've done

We'd appreciate that, thanks.

As this does not seem reproducible, we'll close this for now. We'll keep a close eye on the console to see if similar crashes come in.

**Closed by alexbakker** 2020-06-19 11:36 UTC
Labels: bug
