### ISSUE TITLE
Automatically hightlight newly created item in vault.

### ISSUE THREAD

**Issue by vishalnandagopal** [beemdevelopment/Aegis#596] opened 2020-10-05 18:45 UTC
When you create a new 2FA item in the app using the 'Scan QR code' option, after you confirm the token, edit names and save it, the app can scroll to the newly created item and highlight it the six digit code.

Android 10, Aegis 1.2.1

Thank you for such a useful app!

**Comment by alexbakker** [comment] 2020-10-05 18:46
Duplicate of #116.

**Closed by alexbakker** 2020-10-05 18:46 UTC
