### ISSUE TITLE
Incorrect color

### ISSUE THREAD

**Issue by istudyatuni** [beemdevelopment/Aegis#847] opened 2021-11-14 14:22 UTC
###### Info

* __Version__: 2.0.2
* __Source__: F-Droid
* __Vault encrypted__: No
* __Device__: Samsung Galaxy J1  mini
* __Android version and ROM__: 5.1.1

###### Steps to reproduce

<details>

![image](https://user-images.githubusercontent.com/43654815/141685066-d9dd6be6-19e7-4edc-8884-dd347d495b7e.png)
![image](https://user-images.githubusercontent.com/43654815/141685068-48d1d10a-b2d2-4db0-878a-322c8ea4e64d.png)

</details>

###### What do you expect to happen?

I can see text (more contrast)

###### What happens instead?

Can't see

**Comment by alexbakker** [comment] 2021-11-14 14:27
Duplicate of #754.

**Closed by alexbakker** 2021-11-14 14:27 UTC
Labels: bug

**Comment by istudyatuni** [comment] 2021-11-14 14:45
Oh, I'm sorry, I've been trying to find it, but to no avail
