### ISSUE TITLE
Aegis Desktop app

### ISSUE THREAD

**Issue by HunterShanks** [beemdevelopment/Aegis#798] opened 2021-08-10 00:07 UTC
Hello Aegis team!

I recently switched to your application from andOTP and I've really enjoyed my experience.

I wanted to ask if it would be possible to create a desktop version of your application so that for users who are inclined, could export their automatic backups to a cloud provider and the app would read the backup and import it when you open the application. I imagine this to be similar to Authy except you would leave it to the users discretion on which provider they would trust to sync their back ups to. 

This feature would definitely be more of a convenience feature and technically take away some of the security that come with the 2FA being on a separate device. However, I believe that it would encourage the user base to grow since many often times prefer sacrificing a bit of security for convenience.

**Comment by alexbakker** [comment] 2021-08-10 09:30
Duplicate of #165.

**Closed by alexbakker** 2021-08-10 09:30 UTC
Labels: proposal
