### ISSUE TITLE
Square icons mode

### ISSUE THREAD

**Issue by FrankuFv** [beemdevelopment/Aegis#1455] opened 2024-08-15 23:52 UTC
Hey, very minor UI upgrade request here. As the title says, i'd hope that a square icons could be added one day or an other. the request is purely aesthetic because with certain icons pack (for exemple mine : Oxygen HD and i bet some others), the round shape sometimes crops out some of them. Thx in advance 
Btw thank you all for your work, there already are plenty of cool features that aren't on other 2FA apps, I would understand if this request is considered too superficial lol 
Good day !

![Screenshot_20240816-015159](https://github.com/user-attachments/assets/db8ef805-eb32-4e98-b5fc-3cbd8e8fe4dd)

**Comment by alexbakker** [comment] 2024-08-21 17:41
Duplicate of #216.

**Closed by alexbakker** 2024-08-21 17:41 UTC
Labels: proposal
