### ISSUE TITLE
Implement LastPass Authenticator import

### ISSUE THREAD

**Issue by krejkrejkrej** [beemdevelopment/Aegis#1160] opened 2023-08-11 09:14 UTC
Aegis should be able to import Lastpass Authenticator export files. I don't know java so cannot implement it myself, but I can at least explain what needs to be done.  

Let's start by looking at a JSON export from Lastpass Authenticator, with some inline explanations by me. This format is not documented, so there are some unknowns here. 

```json
{
  "deviceId": "UUID",
  "deviceSecret": "64-byte-random-string",
  "localDeviceId": "UUID",
  "deviceName": "samsung SM-G960F",
  "version": 3,
  "accounts": [
    {
      "accountID": "UUID",
      "lmiUserId": "UUID-or-empty",                         <- unknown field
      "issuerName": "Google - as edited by user",           <- this is what is shown to the user in the app
      "originalIssuerName": "Google",
      "userName": "username@gmail.com - as edited by user", <- this is what is shown to the user in the app
      "originalUserName": "username@gmail.com",
      "pushNotification": false,
      "secret": "OTP-secret-string",
      "timeStep": 30,
      "digits": 6,
      "creationTimestamp": 100001,                          <- see below
      "isFavorite": false,                                  <- see below
      "algorithm": "SHA1",
      "folderData": {
        "folderId": 0,                                      <- use the "folders" array to find the folder name
        "position": 0                                       <- list order for this account
      }
    },
    {
      "accountID": "UUID-for-next-account",
      ...
    }
  ],
  "folders": [
    {
      "id": 1,
      "name": "Favorites",
      "isOpened": true                       <- unknown field
    },
    {
      "id": 2,
      "name": "Private",
      "isOpened": true
    },
    {
      "id": 0,                               <- This folder contains un-grouped entries
      "name": "Other accounts",
      "isOpened": true
    }
  ]
}
```

It's worth mentioning that Favorites are treated slightly differently in LP Authenticator. Starring an entry in LP will move the entry to a group called "Favorites", which is always shown on top in the app. For that reason I chose (in the script below)  to add starred entries to a separate group `LastPass/Favorites` instead if marking as favourite in Aegis. Entries in the default (id=0) (non-)folder are added to the `LastPass` group in Aegis, while entries in other groups are added to the`LastPass/LP-folder-name` group.

The timestamp field has two types of content. My theory is that entries created with a previous app version did not have this field, and a later version just added a sequence number for all existing entries, starting with 100001. Later versions populate it with a milliseconds-since-epoch date. 

This one-liner script will convert a LastPass Authenticator JSON export file to an Aegis export file that can be imported. I hope this info is enough for someone to write the importer code in Aegis. 

```bash
#!/bin/bash
#
# JQ script to convert a LastPass JSON export file to Aegis format.
#
# Export your Lastpass codes to a JSON file on your phone. Transfer the file
# to a computer where jq is installed and:
#
# Usage:
#    lp2aegis < "LastPass Authenticator-1690000000000.json" > LP-for-Aegis.json
#
# Transfer the output file back to your phone and import into Aegis (using Aegis format)
#
# Remember to permanently delete both the Lastpass export file and the Aegis import
# file from your computer and phone after successful import into Aegis.


jq '([.folders[] | { "key": (.id | tostring ), "value": .name }] | from_entries) as $folders |
{
   "version": 1,
   "header": {
      "slots": null,
      "params": null
   },
   "db": {
      "version": 2,
      "entries": [
         (.accounts[] | {
            "type":   "totp",
            "uuid":   .accountID,
            "name":   .userName,
            "issuer": .issuerName,
            "group": (
               "LastPass" +
                  if .folderData.folderId != 0 then
                     "/" + $folders[.folderData.folderId | tostring]
                  else ""
                  end
            ),
            "note": (
               "Created: " + (
                  if .creationTimestamp > 1200300400500 then
                     .creationTimestamp / 1000 | todateiso8601
                  else
                     "unknown"
                  end
               ) +
               if .originalIssuerName != .issuerName then
                  "\n" + "Original Issuer: " + .originalIssuerName
               else ""
               end
               +
               if .originalUserName != .userName then
                  "\n" + "Original Name: " + .originalUserName
               else ""
               end
            ),
            "favorite": null,
            "icon": null,
            "info": {
               "secret": .secret,
               "algo":   .algorithm,
               "digits": .digits,
               "period": .timeStep
            }
         })
      ]
   }
}
'
```

**Comment by gdevenyi** [comment] 2023-09-24 16:23
A complete python script for conversion from LP to Aegis is available here, https://github.com/tghw/lastpass_aegis_convert

**Comment by michaelschattgen** [comment] 2023-11-05 16:11
This is a duplicate of #262, a pull request is welcome but we're not planning on this ourselves.

**Closed by michaelschattgen** 2023-11-05 16:11 UTC
Labels: proposal

**Comment by denisemenov** [comment] 2024-04-16 20:07
If someone needs to export Lastpass Auth json to plain txt or QR codes or Aegis format, then this is how they can do it through node.js with this script - https://github.com/denisemenov/lastpass-auth-export
