### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by MRVMV** [beemdevelopment/Aegis#155] opened 2019-07-02 13:53 UTC
I don't actually know why that just happen but this just happened to me
I have opened the app, passed login screen and changed apps to chrome (kept the app open in recent)
I have only 2 entries in the app btw and both of them have a 30 seconds timeout

Device: S6 edge with 7.0 Android
Btw this too rare to happen with me for other apps and even if happened I never got higher than 4%

![Screenshot_20190702-164756](https://user-images.githubusercontent.com/21023866/60518029-5f32f980-9ce9-11e9-874b-f8d3527fcd13.png)

**Comment by alexbakker** [comment] 2019-07-02 14:23
It's very likely that this is caused by #125 and fixed by #144, but we'll keep this open until we merge that PR and release a new version.

**Comment by alexbakker** [comment] 2019-09-13 12:18
The fix for this is included since version 1.0.

**Closed by alexbakker** 2019-09-13 12:18 UTC
