### ISSUE TITLE
Biometric or password during setup, broken? Results in wrong password everytime!

### ISSUE THREAD

**Issue by No0Vad** [beemdevelopment/Aegis#514] opened 2020-07-08 20:41 UTC
###### Info
I just downloaded the app from the android store, during the setup I choose biometric and set a password.
However, the problem is every time I try to unlock it says wrong password! For testing I choose **a1** as the password.
My fingerprint does not work either.
Same problem occurs if I only choose to encrypt with a password.
But if choose none from the start, and then once I'm in the app choose to protect it with a password, it works.

* __Version__: 1.2
* __Source__: Google Play
* __Vault encrypted:__ Yes
* __Device:__ OnePlus5
* __Android version and ROM:__ 10, Stock

###### Steps to reproduce

1. Clean install or clear the storage of the app.
2. Start the app.
3. In the setup choose Biometric and enter a password, I took **a1** for test
4. Once you enter the app close it.
5. Start the app again, and try to unlock it. Entering **a1** will result in wrong password!

###### What do you expect to happen?

The app to be unlocked with my password chosen during the setup.

###### What happens instead?

Wrong password instead.

###### Log

```
No log
```

**Comment by alexbakker** [comment] 2020-07-08 21:06
Thanks for your report. That is some really strange behavior you're experiencing. Since you're not seeing a crash, it's a bit difficult to assess what's going wrong here without some logs. If I build a debug APK with some additional logging tomorrow, would you be willing to attempt to reproduce the issue with that and capture the log it produces with ADB?

Also, if you select "biometrics", does Aegis prompt you for biometrics after filling in the password, or does it immediately continue to the next slide?

**Comment by No0Vad** [comment] 2020-07-08 21:17
Yeah, it's a strange behaviour. Can you not reproduce it? 
Yeah I can try the debug APK, if you also can show how to **capture the log it produces with ADB**

Yes, it immediately continues to the next slide.

**Comment by alexbakker** [comment] 2020-07-09 07:47
> Can you not reproduce it?

No, unfortunately not.

> Yeah I can try the debug APK, if you also can show how to capture the log it produces with ADB

Great! Here it is: https://alexbakker.me/u/3htschej8f.apk. We wrote a guide for capturing logs with ADB: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb.

> Yes, it immediately continues to the next slide.

Strange, but an important clue. Thanks.

**Comment by No0Vad** [comment] 2020-07-09 11:35
I'm sorry, I'm even more confused right night. Suddenly it works?! I tried uninstalling the app (and dev) and reinstalling them.
Now the setup works, and it prompts for a biometric after entering the password.

I cannot reproduce my own error any more. Could something have been saved somewhere once the password and biometric where setup inside the settings instead, by choosing none during the setup?

Also, excellent guide for capturing the log. Although I had to use **adb logcat -f <ins>/mnt/sdcard/</ins>debug.log**, probably because I'm not rooted?

**Comment by alexbakker** [comment] 2020-07-09 14:21
Thanks for reporting back.

Your case is starting to sound similar to #479, which was also not reproducible. Based on your observations, my suspicion is that something is going wrong when passing state between the different slides in the intro (read: the state is lost in some rare cases). The state is shared through the intent of the parent activity, which is not ideal, but it's the only way to do that with the current library we're using. I'm working on implementing our own intro in [a separate branch](https://github.com/alexbakker/Aegis/commits/new-intro). It's not quite ready yet, but has a better state sharing mechanism.

At this point, I'm inclined to dump a big ugly state check at the end of the intro and crash the app if it's bad, to plug the problem for now. We'll keep this issue open and post updates here.

> Could something have been saved somewhere once the password and biometric where setup inside the settings instead, by choosing none during the setup?

I doubt it. If you uninstalled Aegis or cleared its storage, everything is reset.

> Although I had to use adb logcat -f /mnt/sdcard/debug.log, probably because I'm not rooted?

That's a mistake in the guide. As you noticed, ``adb logcat -f debug.log`` writes the log to a file on the device. It supposed to be ``adb logcat -d > debug.log``. I'll fix it, thanks.

**Comment by alexbakker** [comment] 2020-07-10 19:16
We've released v1.2.1 to temporarily 'fix' this issue, so that users can at least no longer end up in this bad state. I'm going to work on finishing the new intro this weekend. After that has been merged, we'll get v1.2.2 out the door.

**Closed** 2020-08-01 12:11 UTC
Labels: bug
