### ISSUE TITLE
Auto-lock if the app is closed or after a minute

### ISSUE THREAD

**Issue by TobiasDev** [beemdevelopment/Aegis#38] opened 2019-03-29 11:01 UTC
I feel like the app should "auto" lock when you close it, or when you don't open it for a minute or 30 seconds. At the moment, if I don't press the lockpad button it stays open forever.

**Comment by michaelschattgen** [comment] 2019-03-29 11:14
Thanks for creating this issue! However, it's a duplicate of #7.

**Comment by michaelschattgen** [comment] 2019-03-29 11:14
Duplicate of #7

**Comment by TobiasDev** [comment] 2019-03-29 11:29
Sorry... I really suck at searching, I thought I looked at the issues to make sure I didn't create a duplicate.

**Comment by michaelschattgen** [comment] 2019-03-29 11:31
No problem! Closing this issue now.

**Closed by michaelschattgen** 2019-03-29 11:31 UTC
