### ISSUE TITLE
Issue with Samsung Secure Folder

### ISSUE THREAD

**Issue by CitizenXVIL** [beemdevelopment/Aegis#909] opened 2022-04-20 16:40 UTC
###### Info

* __Version__:  2.0.3
* __Source__: Google Play Store
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Samsung Galaxy S22
* __Android version and ROM__: Android 12 (Samsung One UI 4.1)

###### Steps to reproduce

1. Open Secure Folder
2. Open Aegis and unlock vault.
3. Turn off screen, and turn it back on.
4. Return to Aegis and attempt to unlock.

###### What do you expect to happen?

It unlocks and takes me to my vault.

###### What happens instead?

It unlocks and goes to an empty, black screen. 

###### Other:

- Aegis doesn't have this issue when it's not in the Secure Folder.
- A workaround is to close and reopen Aegis.
- This also only seems to occur if the vault is unlocked when the screen is turned off. If Aegis is simply opened and not unlocked, it doesn't have the problem. Similarly, if I manually lock Aegis before the screen turns off, it prevents this problem.

**Comment by alexbakker** [comment] 2022-04-21 17:34
If this is not reproducible outside of a Samsung Secure Folder, I guess there's something about it that makes activities behave differently compared to plain Android.

We don't personally own any Samsung devices, so I'm afraid you'll have to do some digging on your own if you'd like to find the root cause of this issue.

**Comment by alexbakker** [comment] 2022-08-17 10:04
I'm going to close this, because it isn't really actionable until more people with a Samsung device experience this issue and someone can do a deep dive to see whether this is a bug in Aegis or a bug in Samsung Secure Folder.

**Closed by alexbakker** 2022-08-17 10:04 UTC
Labels: bug
