### ISSUE TITLE
Are you able to develop a browser plugin?

### ISSUE THREAD

**Issue by louiejordan** [beemdevelopment/Aegis#1252] opened 2023-12-28 07:13 UTC
As a two-step verification software, Aegis works very well for me. The only improvement I suggest is the addition of a browser plugin. After all, most scenarios requiring 2FA occur when using a PC.

**Comment by alexbakker** [comment] 2023-12-28 07:20
Duplicate of #165.

**Closed by alexbakker** 2023-12-28 07:20 UTC
Labels: proposal
