### ISSUE TITLE
Unable to import vault

### ISSUE THREAD

**Issue by Quintus19** [beemdevelopment/Aegis#1043] opened 2022-11-28 11:07 UTC
### Version

v2.1

### Source

GitHub

### Vault encryption

Yes

### Device

LG G4

### Android version

Android 6.0

### Steps to reproduce

1- Open Aegis
2- Tap the three dots then tap "Settings"
3- Tap "Import & Export"
4- Tap "Import from file" and select "Aegis" option
5- Select the backup file

### What do you expect to happen?

For Aegis to import the vault successfully.

### What happens instead?

Displays an error message instead of importing the vault.

"An error occurred while trying to read the file

java.io.FileNotFoundException: /storage/emulated/0/aegis-export-20221128-135410.json: open failed: EACCES (Permission denied)

![Capture+_2022-11-28-13-56-53](https://user-images.githubusercontent.com/119014876/204262914-76d4f3bb-3a27-4c0b-9dfe-cdcb9576e8a0.png)

**Comment by alexbakker** [comment] 2022-11-28 17:29
Duplicate of #1031.

**Closed by alexbakker** 2022-11-28 17:29 UTC
Labels: bug
