### ISSUE TITLE
2FA Authenticator Import Error

### ISSUE THREAD

**Issue by sick13** [beemdevelopment/Aegis#893] opened 2022-03-06 17:57 UTC
###### Info

* __Version__: 2.0.2
* __Source__: (F-Droid)
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__:S10+
* __Android version and ROM__:A11 OneUi 3.1

###### Steps to reproduce
I am trying to import 2FA Authenticator Backup file [*.2fas]

https://play.google.com/store/apps/details?id=com.twofasapp&hl=en_US&gl=US

###### What do you expect to happen?

Import Authentication numbers

###### What happens instead?

it fails with the following message:

an error occured while trying to read the file

com.beemdevelopment.ageis.importers.databaseimporterExcepetion:unsupported schema version:2

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment] 2022-03-06 17:58
Duplicate of #892.

**Closed by alexbakker** 2022-03-06 17:58 UTC
Labels: bug

**Comment by sick13** [comment] 2022-03-06 18:00
sorry did not see that!
