### ISSUE TITLE
Apply image changes without checkmark button, or prompt for confirmation

### ISSUE THREAD

**Issue by lwolff** [beemdevelopment/Aegis#416] opened 2020-05-15 23:26 UTC
Currently, choosing a new image then clicking "SAVE" will not save the image, a user instead has to click a small checkmark in the corner first. Most users would expect the image to be saved when the "SAVE" button is pressed.

**Comment by alexbakker** [comment] 2020-05-16 06:40
Duplicate of #252.

**Closed by alexbakker** 2020-05-16 06:40 UTC
Labels: proposal
