### ISSUE TITLE
Request for Aegis Development for Windows/Linux

### ISSUE THREAD

**Issue by enesehs** [beemdevelopment/Aegis#1452] opened 2024-08-09 12:18 UTC
I believe that by developing Aegis Auth for Windows and Linux, you will continue to uphold your commitment to providing secure and efficient solutions to a wider audience. Your attention to this request would be greatly appreciated, and I am confident that it will contribute positively to your brand’s reputation and user base.

Thank you for considering this request. I look forward to your positive response.

**Comment by alexbakker** [comment] 2024-08-09 12:42
Duplicate of #165.

**Closed by alexbakker** 2024-08-09 12:42 UTC
Labels: proposal
