### ISSUE TITLE
Possible computer implementation? 

### ISSUE THREAD

**Issue by 737simpilot** [beemdevelopment/Aegis#920] opened 2022-05-28 15:34 UTC
Is there a computer implementation of this App by chance? I'm wondering if Electron could be used so it could run cross platform in Windows, Linux and OSX? 

This is why I chose Authy early on for cross platform ability. i.e., Android and Windows.

**Comment by alexbakker** [comment] 2022-05-28 15:36
Duplicate of #165.

**Closed by alexbakker** 2022-05-28 15:36 UTC
Labels: proposal

**Comment by 737simpilot** [comment] 2022-05-28 15:41
And wow, didn't realize this was such a requested feature.
