### ISSUE TITLE
one barcode to rule them all

### ISSUE THREAD

**Issue by MrAngelus** [beemdevelopment/Aegis#960] opened 2022-08-15 19:59 UTC
I know you cab select one entry and make a barcode for entry into another app

Would it be possible to select more then one entry possibly all of them and making a barcode for everything I beleve you can do this with google authenticator  but as far as I can tell not with Aegis

**Comment by alexbakker** [comment] 2022-08-17 08:30
Duplicate of #551.

**Closed by alexbakker** 2022-08-17 08:30 UTC
Labels: proposal
