### ISSUE TITLE
Request linux desktop support

### ISSUE THREAD

**Issue by coolst3r** [beemdevelopment/Aegis#1269] opened 2024-01-23 23:44 UTC
a flatpak for linux so it can be used on arch or deb

**Comment by michaelschattgen** [comment] 2024-01-23 23:49
Duplicate of #165.

**Closed by michaelschattgen** 2024-01-23 23:49 UTC
Labels: proposal

**Comment by coolst3r** [comment] 2024-01-24 00:43
you have 10 requests for desktop platform why not do it

**Comment by jidanni** [comment] 2024-02-12 02:50
Or how about a CLI version. No fancy graphics needed.

Here's mine. (I used perl to not expose my codes. Not even for a minute.)

```
$ 2fa fac|perl -pwle 's/\d{6}/sprintf "%6d", 1000000 * rand()/e'
==== Facebook ====
939765
826726
795519
372733
652370
The first code is for following next 30 second segment,
which starts in 8 seconds, or in fact now, too, usually.
I also sent first code to wl-copy!
```

As you see mine even copies the six digits to the clipboard.

Anyway the only thing I didn't make was the hard part of getting the database from the network.

I have to maintain the database by hand.
