### ISSUE TITLE
Linux Desktop .AppImage version?

### ISSUE THREAD

**Issue by gnrlus** [beemdevelopment/Aegis#865] opened 2021-12-29 16:00 UTC
Can you make your app available on Linux desktop as pgp-signed .AppImage that runs on any distro and kernel?

For those of us wishing to ditch smart phones and not have to juggle devices this would be a massive improvement for authentication methods. I haven't found a consumer-grade, hassle-free Linux solution.

Also, accounts with sites requiring this kind of authentication are at risk of lock-out should anything happen to one's phone. Having a PC alternative would be a life saver.

Thanks for such a great app, by the way!

**Comment by Hacker437** [comment] 2022-01-02 16:38
Duplicate of #165

**Closed** 2022-01-03 20:41 UTC
Labels: proposal
