### ISSUE TITLE
Electronic Arts Unsupported Protocol: HTTPS

### ISSUE THREAD

**Issue by umitseyhan75** [beemdevelopment/Aegis#803] opened 2021-08-28 20:10 UTC
###### Info

* __Version__: 2.0.1
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Nokia 8
* __Android version and ROM__: Android 9, Security Patch 1 October 2020

###### Steps to reproduce
1. Go to their site : [Link](https://www.ea.com/)
2. Login into your account
3. Head into the account settings and than security tab
4. Activate the 2FA with auth app under login verification
5. Scan the QR Code

###### What do you expect to happen?

Get the related info to the app and continue

###### What happens instead?

Error saying: `com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: https`

###### Log

```
com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: https
```

**Comment by alexbakker** [comment] 2021-08-29 10:59
Duplicate of #376

**Closed by alexbakker** 2021-08-29 10:59 UTC
Labels: bug
