### ISSUE TITLE
Unable to pick icon from downloaded folder

### ISSUE THREAD

**Issue by Daniel15** [beemdevelopment/Aegis#523] opened 2020-07-14 02:52 UTC
#### Info

* __Version__: 1.2.1
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samsung Galaxy S10 
* __Android version and ROM:__ Android 10, standard Samsung ROM

###### Steps to reproduce

Long-tap an entry
Tap the edit button
Tap the placeholder icon
Try to select a new icon

###### What do you expect to happen?
Allow me to use a file browser (eg Solid Explorer) to choose a file. 

###### What happens instead?
It's only showing me options to use the gallery or Google Photos to select an icon, neither of which seem to let me select a downloaded file.

**Comment by alexbakker** [comment] 2020-07-14 07:57
Duplicate of #505.

**Closed by alexbakker** 2020-07-14 07:57 UTC
Labels: bug
