### ISSUE TITLE
Importing Same Codes, Creates Duplicates

### ISSUE THREAD

**Issue by phptek** [beemdevelopment/Aegis#890] opened 2022-03-03 08:57 UTC
###### Info

* __Version__:  2.0.2
* __Source__: (Google Play)
* __Vault encrypted__: Yes
* __Device__: Galaxy S9
* __Android version and ROM__: 10 

###### Steps to reproduce

1. Google Authenticator: Export a series of individual MFA codes
2. Google Authenticator: Generate QR code as backup
3. Aegis: Select orange "+" icon
4. Aegis: Select "Scan QR code"
5. Aegis: Scan Google Authenticator's QR code(s)
6. Aegis: Repeat steps 3-5. Observe all imported records have been duplicated

Why would anyone do this? Good question. I live overseas from a family member and I needed an MFA device's codes exported and sent securely over Signal. I wan't sure all records had been properly imported so I tried again several times and ended up with dozens of records, each of which was a dupe of the original.

###### What do you expect to happen?

Several ideas:

1. Don't do anything (or perhaps silently delete all identical records and re-import what would otherwise become a duplicate record)
2. Warn the user and do nothing

...

###### What happens instead?

All records are duplicated.

...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment] 2022-03-04 11:49
Duplicate of #453.

**Closed by alexbakker** 2022-03-04 11:49 UTC
Labels: bug
