### ISSUE TITLE
Biometric unlock doesn't work after reinstall, although this option is active in settings

### ISSUE THREAD

**Issue by alpenblauwtje** [beemdevelopment/Aegis#1375] opened 2024-05-08 13:38 UTC
### Version

3.0.1

### Source

F-Droid

### Vault encryption

Yes (with biometric unlock)

### Device

A52s

### Android version

14

### Steps to reproduce

I uninstalled and re-installed Aegis. I open the most recent backup file in my backup location and enter the password. In _Settings > Security_ I noticed the option _Biometric unlock_ is active. 
I exit Aegis and open it again. I can't unlock with fingerprint and I have to enter my password instead.
This issue can be "fixed" by disabling and enabling the option _Biometric unlock_.

### What do you expect to happen?

That biometric unlock works if this option is active. Alternatively disable this option after reinstall and opening a backup file.

### What happens instead?

See steps to reproduce.

**Comment by alexbakker** [comment] 2024-05-17 13:24
Duplicate of #1126.

**Closed by alexbakker** 2024-05-17 13:24 UTC
Labels: bug
