### ISSUE TITLE
Automatic Backup Doesn't Show Cloud Storage

### ISSUE THREAD

**Issue by christantoan** [beemdevelopment/Aegis#772] opened 2021-06-12 11:46 UTC
###### Info

* __Version__: 2.0
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 7 Pro
* __Android version and ROM__: 10 / Oxygen OS 10.0.11.GM21BA

###### Steps to reproduce

In the Backups page in Settings, choose to enable automatic backup of the vault

###### What do you expect to happen?

SAF opens with the option to use cloud storage (at least, signed-in Google Drive)

###### What happens instead?

SAF opens with no option to use cloud storage
![Screenshot_20210612-183348](https://user-images.githubusercontent.com/7300310/121774822-5a05a700-cbae-11eb-856c-caa04fa8338c.png)

**Comment by alexbakker** [comment] 2021-06-12 11:47
Duplicate of #759.

**Closed by alexbakker** 2021-06-12 11:47 UTC
Labels: bug
