### ISSUE TITLE
Offer export and import of vault into otpauth URIs etc. app-neutral formats, and import of such files too

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#348] opened 2020-04-08 00:45 UTC
Users might have many keys to import, from simple CSV "host,key" formats, to more complex
https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93#gistcomment-3244864
formats.
Users need an example of what such basic pairs would look like in
https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md format.
That way they could write quick scripts to convert, and install their keys via "Import from Aegis" radio button.

**Comment by jidanni** [comment] 2020-04-08 00:48
Therefore, show e.g., how [those three items](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93#gistcomment-3244864) would look in a fully complete [Aegis vault file](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md).

**Comment by jidanni** [comment] 2020-04-09 13:12
In the promotional material you could empathize: other apps, like Authy,
might let you transfer and backup your keys, but it is all in their
cloud. They never let you get your hands on your own keys! Consumer
lock-in! That's where Aegis is different. Though Ageis might lack fancy
clouds, however Aegis lets you import and export your keys to and from
standard interchange formats. No consumer lock-in!

**Comment by jidanni** [comment] 2020-04-09 13:14
Maybe Aegis should have an "export (entire) vault to otpauth:// strings" function,
so the user can be free to migrate away from Aegis if he wishes.

```
#!/usr/bin/perl
# Convert plain text Aegis vault format into otpauth URIs
# Copyright       : https://www.fsf.org/copyleft/gpl.html
# Author          : Dan Jacobson -- https://www.jidanni.org/
# Created On      : Thu Apr  9 11:13:10 2020
# Last Modified On: Thu Apr  9 12:44:18 2020
# Update Count    : 54
use strict;
use warnings FATAL => q(all);
use JSON;
use URI;
use URI::QueryParam;
local $/;
local $_ = <>;
my $p = decode_json $_;
for ( @{ $p->{db}->{entries} } ) {
    my $u = URI->new( "otpauth://" . %{$_}{type} . "/" . %{$_}{name} );
    my %i = %{ $_->{info} };
    for my $k (qw/icon info name type uuid/) {
        delete $_->{$k};
    }
    $u->query_form_hash( %$_, %i );
    print $u->as_string, "\n";
}

```

**Comment by jidanni** [comment] 2020-04-09 13:20
And of course also offer importing a file full of otpauth URIs back into Aegis,
```
#!/usr/bin/perl
# Convert otpauth URIs into clear text Aegis vault format
# Copyright       : https://www.fsf.org/copyleft/gpl.html
# Author          : Dan Jacobson -- https://www.jidanni.org/
# Created On      : Wed Apr  8 08:59:06 2020
# Last Modified On: Thu Apr  9 21:19:27 2020
# Update Count    : 138
use strict;
use warnings FATAL => q(all);
use JSON;
use URI;
use URI::QueryParam;
use UUID 'uuid';
binmode STDOUT;
my %h = (
    db     => { version => 1 },
    header => {
        params => undef,
        slots  => undef
    },
    version => 1,
);
while (<>) {
    next unless /otpauth:.*/;
    my $u = URI->new($&);
    push @{ $h{db}->{entries} }, {
        icon => undef,
        info => {
            algo   => "SHA1",    #set a default
            period => 30,        #set a default
            digits => 6,         #set a default
            %{ $u->query_form_hash },
        },
        name => ( $u->path_segments )[-1],
        type => $u->authority,
        uuid => uuid(),
    };
}
for ( @{ $h{db}->{entries} } ) {
    $_->{info}->{digits} += 0;
    $_->{info}->{period} += 0;
    $_->{issuer} = delete $_->{info}->{issuer};
    ## Wonder what else we should clean up...
    ## https://github.com/google/google-authenticator/wiki/Key-Uri-Format
    ## (We see there algo should be algorithm, etc...)
}
my $json = JSON->new;
$json = $json->canonical(1);
print $json->pretty->encode( \%h );

```

**Comment by jidanni** [comment] 2020-04-09 13:50
https://github.com/Authenticator-Extension/Authenticator/issues/282#issuecomment-464497512

**Comment by jidanni** [comment] 2020-04-09 13:56
https://github.com/helloworld1/FreeOTPPlus/issues/30#issuecomment-464608515

**Comment by jidanni** [comment] 2020-04-09 13:57
Anyway, not only should a file full of otpauth's, one per line be offered as a "backup" format, it should also be an "import" and "export" format.

**Comment by alexbakker** [comment] 2020-04-09 16:09
As you seem to have already discovered, this is a duplicate of #138.

**Closed by alexbakker** 2020-04-09 16:09 UTC
Labels: proposal
