### ISSUE TITLE
Fail to import from Steam 3.7.0

### ISSUE THREAD

**Issue by teishahbc** [beemdevelopment/Aegis#1220] opened 2023-10-31 07:06 UTC
### Version

2.2.2

### Source

F-Droid

### Vault encryption

Yes

### Device

Oneplus 8 pro

### Android version

Android 11

### ROM

Hydrogen OS 11

### Steps to reproduce

0. Device rooted, Steam app version 3.7.0
1. Go to settings - import from app -Steam
2. Granted root rights to Aegis
3. An error occurred : An error occurred while trying to read the file
com.beemdevelopment.aegis.importers.DatabaseImporterException: Empty directory: /data/user/0/com.valvesoftware.android.steam.community/files 

### What do you expect to happen?

Import from Steam app successfully 

### What happens instead?

An error occurred

**Comment by alexbakker** [comment] 2023-11-04 15:56
Duplicate of #986.

**Closed by alexbakker** 2023-11-04 15:56 UTC
Labels: bug
