### ISSUE TITLE
Dark mode in main menu, doesn't work if you don't have any entries.

### ISSUE THREAD

**Issue by Millichrome** [beemdevelopment/Aegis#37] opened 2019-03-28 18:22 UTC
I noticed that dark mode does not become enabled until you add some entries to Aegis. If you don't have any accounts in Aegis and you select dark mode, the main menu does not use the dark theme. 

This is a minor issue, but it would be good to fix for the sake of consistency.

Thank you for you work on this. I am probably going to switch from AndOTP. I like the UI more and I am hoping there will be more active development with Aegis.

**Comment by michaelschattgen** [comment] 2019-03-28 18:44
Thanks for opening this issue!

Just to make sure, by 'main menu' you mean the screen where all the account show up right?
Unfortunately I can't find a way to reproduce this. My screen looks like this:
<img src="https://user-images.githubusercontent.com/7524012/55184087-98f7df80-5191-11e9-96d9-753f7d8bb38e.png"  width="150">


On what device and Android version are you experiencing this bug?

**Comment by Millichrome** [comment] 2019-03-28 19:13
Yes, the screen with all the accounts.

This issue was present on stock Android Pie 9.0 Mi A1 and LOS 15.1 Nexus 6P (with root). I understand if you can't support custom ROMs, but this happened on the stock Mi A1 too.

For what it's worth, the Nexus 6P started using dark mode after a few restarts (I didn't add any accounts, but I might have exported an empty backup file). Dark mode on the Mi A1 started working after I manually added an account via QR code.

If you want I can try and do a complete reinstall and send you the relevant log files (you would need to tell me what to send). Let me know.

**Comment by alexbakker** [comment] 2020-05-25 18:25
A lot has changed in the theming of Aegis after this issue was first reported. And since this is an issue we've never been able to reproduce, I'm going to close this for now. If the issue still appears, feel free to reopen it.

**Closed by alexbakker** 2020-05-25 18:25 UTC
Labels: bug
