### ISSUE TITLE
[UX] Image Editing Tweak: Save current view/crop when pressing save button for entry

### ISSUE THREAD

**Issue by AyoungDukie** [beemdevelopment/Aegis#345] opened 2020-04-06 21:18 UTC
First just want to say thank you for all of your hard work, this really is a great app! Just came across it today, and am loving it!

I had a thought about a small UX request, as currently when editing the picture for an entry, the user flow is to:
- Tap the current icon
- find an icon image in their gallery app of choice
- select that image
- Select the checkmark icon at the bottom right of the dark-gray crop overlay screen
- Press save at the top right

Especially when cropping an image after selecting, this process seems somewhat self-evident. However in a case were adding premade/pre-sized/pre-cropped icons (ie from the community icon pack), the crop overlay aligns perfectly with the background, making it easier to miss that the image is in "edit" mode. If one does miss this, and select the Save button at the top, the image will not be saved, and the user will have to start the process over again.

Would it then be possible to modify the image selection behavior with one (or a combination) of tweaks for better usability:
 - A text tooltip indicating "Crop/Edit" mode is active
 - Save currently shown crop/edit of image when "Save" is selected
 - Launch a dialogue asking the user to save/discard the unsaved changes (or cancel the action of saving) 

These are just some ideas about small tweaks, but feel free to suggest others or modify them as needed. Just seems like an area where the app could improve with potentially few changes.

**Comment by ukanuk** [comment] 2020-04-07 07:31
I've also made the same mistake repeatedly because the icons suggested from [krisu/Aegis-icons](https://github.com/krisu5/Aegis-icons) are all already perfectly sized, and my eye and finger immediately go for "save" rather than realizing I need to save the default crop.

This seems the most straightforward option to me:
> * Save currently shown crop/edit of image when "Save" is selected

But another potential UX flow could be
* Reverse the default. Instead of assuming user wants to edit the image and providing a checkmark button to save changes after edits, assume user doesn't want to edit image and provide an edit/crop button in case the default is inadequate.

**Comment by ukanuk** [comment] 2020-04-07 07:38
Also, this is duplicated issue #252, and related to issue #80.

**Comment by alexbakker** [comment] 2020-04-07 09:36
This is indeed a duplicate of #252. Thanks for the kind words and suggestion though!

**Closed by alexbakker** 2020-04-07 09:36 UTC
Labels: proposal
