### ISSUE TITLE
Add support for 2FAS Authenticator backup import with schema version `^4.0.0`

### ISSUE THREAD

**Issue by alexandre-eliot** [beemdevelopment/Aegis#1304] opened 2024-03-15 14:00 UTC
### Version

2.2.2

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

OnePlus 6

### Android version

11

### ROM

OxygenOS 11.1.2.2

### Steps to reproduce

- Export a backup file without password through the app 2FAS Authenticator.
- Import the `.2fas` file using the option `Import from file` -> `2FAS Authenticator`

### What do you expect to happen?

- The file is uploaded and interpreted
- All credentials are stored in the vault

### What happens instead?

An error panel pops up with the message :
```
com.beemdevelopment.aegis.importers.DatabaseImporterException: Unsupported schema version: 4
```

**Comment by alexbakker** [comment] 2024-03-16 11:20
Duplicate of #1243. The fix is included in [v3.0-beta1](https://github.com/beemdevelopment/Aegis/releases/tag/v3.0-beta1).

**Closed by alexbakker** 2024-03-16 11:20 UTC
Labels: bug
