### ISSUE TITLE
Decorative animations not respecting system animation setting

### ISSUE THREAD

**Issue by Eiqnepm** [beemdevelopment/Aegis#1122] opened 2023-04-22 18:22 UTC
### Version

2.1.3

### Source

Google Play

### Vault encryption

No

### Device

One UI 5.1

### Android version

Android 13

### Steps to reproduce

- Open app
- Change sort order
- Open setting submenu
- Return to settings from settings submenu

### What do you expect to happen?

Decorative animations to respect Android system setting and not play

### What happens instead?

Decorative animations are ignoring Android system setting

<img src="https://i.imgur.com/mUsyZ1A.gif" height="480"> <img src="https://i.imgur.com/jwAgas7.gif" height="480"> <img src="https://i.imgur.com/9YdKWDr.gif" height="480">

**Comment by alexbakker** [comment] 2023-04-23 17:35
Duplicate of #930.

**Closed by alexbakker** 2023-04-23 17:35 UTC
Labels: bug
