### ISSUE TITLE
Paint the codes if the timer is below x seconds

### ISSUE THREAD

**Issue by Kaerbr** [beemdevelopment/Aegis#737] opened 2021-05-04 15:13 UTC
In principle, I find the status display on the top edge good, but I always overlook this when copying or typing the code, which then ends up in the fact that I copy an expired code.
So my suggestion is to color the codes red from 3 or 5 seconds before, till expiration.

Time and color can certainly still be discussed here! (:

**Comment by alexbakker** [comment] 2021-05-04 15:14
Duplicate of #411.

**Closed by alexbakker** 2021-05-04 15:14 UTC
Labels: proposal
