### ISSUE TITLE
Favicons by url

### ISSUE THREAD

**Issue by Veia7e** [beemdevelopment/Aegis#1553] opened 2024-11-26 16:09 UTC
Hello

Do you plan to add a feature for fetching favicons by URL in the future? I understand that you prefer not to give the app internet access, but perhaps this could be implemented through a simple intermediary layer, maybe even with the help of another app that does have internet access?

There are too many new websites and apps emerging too quickly, and icon packs are becoming increasingly outdated (they can't keep up fast enough, at least not without AI assistance). I’ve downloaded all the suggested icon packs, and they only covered about 20% of my sites.

Your app is fantastic (and, for me personally, the best one out there), and this feature would truly be a killer feature for me, as I haven't seen it in other popular apps of this level. I really enjoy using this functionality in KeePassXC, and I hope that someday I’ll be able to use it here as well.

PS
I tried going to websites and downloading favicons myself, but they turned out too clumsy in the app, maybe because of different sizes, paddings, round areas for the image, I don't know

**Comment by alexbakker** [comment] 2024-11-26 17:00
Duplicate of #667

**Closed by alexbakker** 2024-11-26 17:00 UTC
Labels: proposal

**Comment by poelzi** [comment] 2024-12-08 15:10
I can understand this, but from a user-ability perspective this is kind of annoying. Just came here to open this bug like 5 others before because the default look of Aegis is ....

As a user, I want to add a code and see a icon instead of a letter. Now I'm 20 minutes searching for a icon pack that maybe gets updates, for sure does not support all the sites I'm using....

Maybe a proxy that has internet access and searches of a icon to select and just stores them freshly cleaned through a rust written image writer lib ?
Should be save enough
