### ISSUE TITLE
First biometric attempt fails

### ISSUE THREAD

**Issue by Cyrris** [beemdevelopment/Aegis#1038] opened 2022-11-25 06:51 UTC
### Version

2.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 4a

### Android version

Android 13

### Steps to reproduce

- Open Aegis after ensuring it is set to be in a locked state after using the back button or minimising
- See the biometric prompt slide up
- Press finger on fingerprint scanner on back of phone
- Observe nothing happens. No vibration, no error pop-up, nothing.
- Press "Cancel" on the biometric prompt
- Select the "Or tap here to use biometrics" link on the Aegis login screen
- See the biometric prompt slide up
- Press finger on fingerprint scanner on back of phone
- Observe successful login

### What do you expect to happen?

Aegis should unlock immediately without needing to close and reopen the biometric prompt

### What happens instead?

Nothing happens. 

If I press "Cancel" on the biometric prompt, it disappears as expected and I can log in via password. If I then select the "Or tap here to use biometrics" link on the Aegis login screen, the biometric prompt slides back up _and can be successfully used to log in_.

The issue only appears to occur when the app is initially opened and requires unlocking. If biometrics are required once the app has already initially opened, it appears to work okay. All other apps on the phone are working fine with biometrics, and this issue appears to have only begun after the v2.1 update the other day.

What I have noticed is that when this issue occurs, I can briefly see what appears to be two prompts sliding up from the bottom of the screen when the biometric prompt appears. When the issue does not occur (such as after using the "Or tap here to use biometrics" link, or setting biometrics within the Settings menu), this appearance of two animations does not occur.

If I press the back button while the prompt is displayed, the biometric prompt remains on screen even though Aegis has minimised in the background. If I then Cancel the prompt and re-open Aegis, I can log in as expected with biometrics.

I have cleared the app cache, cleared the app data, and uninstalled/reinstalled the app to no avail.

**Comment by alexbakker** [comment] 2022-11-28 18:23
Thanks for the report. I'm not seeing this issue on my Pixel 5. It's odd that you started seeing this after the update from v2.0.3 -> v2.1, since we have not updated ``androidx.biometric`` between those releases. A full logcat of you reproducing the issue might be helpful here. The system usually logs some extra info is something goes wrong initializing biometric authentication

**Comment by Cyrris** [comment] 2022-12-01 10:10
OK, apologies in advance if I've not done this right (not a developer, first time grabbing logs this way). Attached is just a snippet from opening the Aegis app and seeing the prompt slide up twice. 
[logcat1.txt](https://github.com/beemdevelopment/Aegis/files/10131370/logcat1.txt)

**Comment by un1c3** [comment] 2022-12-02 08:03
I can recreate the issue too on my Pixel 4XL with Graphene OS. Attached logcat.

[Logcat.md](https://github.com/beemdevelopment/Aegis/files/10139181/Logcat.md)

**Comment by PatrikStaehli** [comment] 2022-12-02 08:12
I also have the same issue on my Pixel 4a (4G). I'm a new user, so I can't say if it worked with older versions. Android 13 with November patch level.
What might help in the search of the cause: it looks like the 'unlock the vault' biometric popup slides up twice in very short succession (barely noticeable, but definitely there, if you pay attention) when starting the app. After hitting 'cancel' and hitting 'biometrics' again, it only slides up once and works.

**Comment by lnusilbu** [comment] 2022-12-03 04:22
I am having the same bug on Aegis version 2.1.

**Comment by alexbakker** [comment] 2022-12-03 16:20
Thank you all for the extra info. From the logs, it looks like the first of the two biometric prompts is being cancelled for some reason, but it's not immediately clear to me if Android is doing that, or if we are doing that.

I've added some extra logging in [this debug APK](https://alexbakker.me/u/8iz1qpqdc2.apk). Could you try to reproduce with that and capture a log once more?

**Comment by un1c3** [comment] 2022-12-03 16:44
I'm unable to reproduce the issue with the debug build.

[Logcat_debug.md](https://github.com/beemdevelopment/Aegis/files/10146935/Logcat_debug.md)

**Comment by Mello3vnik** [comment] 2022-12-03 17:04
Are others with this problem also on GrapheneOS ?
Pixel are the only phone mentioned so far, and un1c3 is the only one to specify that he's on it, like me.
I wonder if there is a connection?

**Comment by lnusilbu** [comment] 2022-12-03 17:30
I am also on GrapheneOS. The bug only happens occasionally. Next time I catch it on the debug build I'll send a log.

**Comment by alexbakker** [comment] 2022-12-03 17:32
@un1c3

> I'm unable to reproduce the issue with the debug build.

Interesting! It's possible that this was fixed in bb4450a00b33cce4527cfdbd4df04e709b690db4. Anyone still able to reproduce the issue on the debug build?

**Comment by lnusilbu** [comment] 2022-12-04 00:16
No. Seems fixed in the debug build to me.

**Comment by alexbakker** [comment] 2022-12-04 11:53
Great! The fix will be included in the next minor release.

**Closed by alexbakker** 2022-12-04 11:53 UTC
Labels: bug
