### ISSUE TITLE
Add "No Group" option to group filter selection UI

### ISSUE THREAD

**Issue by blueawful** [beemdevelopment/Aegis#934] opened 2022-06-24 21:51 UTC
Scenario:
As a new user, I imported a lot of accounts into Aegis. I created groups and started to organize my accounts into them, but had trouble determining which ones still needed to be assigned a group.

Proposal:
Add a "No Group" option to the group selection screen, which would match and display any account without a group assigned.

**Comment by alexbakker** [comment] 2022-06-25 08:59
Duplicate of #826.

**Closed by alexbakker** 2022-06-25 08:59 UTC
Labels: proposal
