### ISSUE TITLE
Support WebDav backup

### ISSUE THREAD

**Issue by zzh4n** [beemdevelopment/Aegis#820] opened 2021-09-13 03:23 UTC
The current backup method needs to manually move the backup files to other devices, which is very cumbersome (Android's backup system is not available in China). Using WebDav can make backup easy.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-13 15:16
Would this allow it to support [EteSync](http://github.com/etesync/android)?

**Comment by alexbakker** [comment] 2021-09-15 13:00
This is a duplicate of #630. See my comment here: https://github.com/beemdevelopment/Aegis/issues/630#issuecomment-746134134.

**Closed by alexbakker** 2021-09-15 13:00 UTC
Labels: proposal
