### ISSUE TITLE
Custom text field

### ISSUE THREAD

**Issue by sami-djo** [beemdevelopment/Aegis#795] opened 2021-08-06 22:48 UTC
It would be great if I could add some text to an entry. For instance, Microsoft account gives me a "recuperation code" along with the 2fa Qr-Code. I don't want to store this code in my password manager for obvious reasons. I think the best place to store this code is in Aegis.
Could it be possible to add an extra text field for each entry where I could put some text ? Thanks !

**Comment by alexbakker** [comment] 2021-08-10 09:27
Duplicate of #782.

**Closed by alexbakker** 2021-08-10 09:27 UTC
Labels: proposal
