### ISSUE TITLE
Aegis for iOS

### ISSUE THREAD

**Issue by AzagraMac** [beemdevelopment/Aegis#796] opened 2021-08-09 18:13 UTC
First of all THANK YOU to all who make this great OpenSource App possible, I have already made several donations because of how amazing and useful it is. 

But... Are there any plans to release the App for iOS users? Even if it was paid, I would pay for it, being able to export Android settings to iOS and vice versa would be amazing. First of all THANK YOU to everyone who makes this great OpenSource App possible, I have already made several donations because of how amazing and useful it is. 

A big hug to all of you.

**Comment by alexbakker** [comment] 2021-08-10 09:27
Thanks for the kind words! This is a duplicate of #290 though.

**Closed by alexbakker** 2021-08-10 09:27 UTC
Labels: proposal
