### ISSUE TITLE
 Will there be a PC app ?

### ISSUE THREAD

**Issue by MaximusPanin** [beemdevelopment/Aegis#1224] opened 2023-11-21 17:48 UTC
I would like a PC app in the future.

**Comment by EhrenmannXD** [comment] 2023-11-22 09:56
Check [the FAQ](https://github.com/beemdevelopment/Aegis/blob/master/FAQ.md) 

> Can you port Aegis to iOS/Windows/MacOS/Browser Extension?
> We don't have plans to port Aegis to other platforms.

**Comment by alexbakker** [comment] 2023-11-22 12:40
Duplicate of #165.

**Closed by alexbakker** 2023-11-22 12:40 UTC
Labels: proposal
