### ISSUE TITLE
Add visible clues when less than 10 seconds remaining for the code

### ISSUE THREAD

**Issue by davchana** [beemdevelopment/Aegis#1246] opened 2023-12-16 01:35 UTC
the code changes every 30 seconds of clock. sometimes I copy and paste the code to website,  some websites are strict,  they accept only current 30 second code (like uscis.gov)

the app should either change the code color to red, or some background light/minimal flashing to show when clock has seconds between 21 & 30; and 51 & 00.
l

**Comment by alexbakker** [comment] 2023-12-16 11:57
Duplicate of #411.

**Closed by alexbakker** 2023-12-16 11:57 UTC
Labels: proposal
