### ISSUE TITLE
Delete a entry by searching can cause vaults list empty

### ISSUE THREAD

**Issue by gracie95** [beemdevelopment/Aegis#1123] opened 2023-04-25 17:27 UTC
### Version

v2.1.3

### Source

F-Droid

### Vault encryption

Yes

### Device

Galaxy A52

### Android version

Android 13

### Steps to reproduce

https://user-images.githubusercontent.com/107738923/234354720-03df54ef-eec3-474e-b208-42d312c54630.mp4

1. Go and search a entry (with single result)
2. Delete the entry
3. Remove the text you type.
4. Entries become empty

### What do you expect to happen?

It should show all entries.

### What happens instead?

Entries are empty.

**Comment by alexbakker** [comment] 2023-04-25 19:36
Duplicate of #1099.

**Closed by alexbakker** 2023-04-25 19:36 UTC
Labels: bug
