### ISSUE TITLE
Failed import to aegis in ldplayer

### ISSUE THREAD

**Issue by 3xploiton3** [beemdevelopment/Aegis#1085] opened 2023-01-14 01:29 UTC
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

ldplayer4.0.83

### Android version

7.1.2

### Steps to reproduce

error to import json

from aegis android to aegis ldplayer

### What do you expect to happen?

succesful import

### What happens instead?

error

![image](https://user-images.githubusercontent.com/19517680/212444282-b3e566db-d844-475e-b6e1-9103df9a096d.png)

**Comment by alexbakker** [comment] 2023-01-15 21:46
Duplicate of #1031.

**Closed by alexbakker** 2023-01-15 21:46 UTC
Labels: bug
