### ISSUE TITLE
Automatic Cloud Backup

### ISSUE THREAD

**Issue by nagha95** [beemdevelopment/Aegis#587] opened 2020-09-05 01:48 UTC
Add an automatic cloud backup option for the encrypted vault file, to a choice of providers such as Google Drive, OneDrive and Dropbox. The file would sync on any changes or updates.

This would be a pretty nice option and alternative to manual backup and local storage.

**Comment by DaVoodoo** [comment] 2020-09-08 17:48
I second this proposal.

**Comment by StefanBrand** [comment] 2020-09-09 07:21
And please don't forget a FLOSS option like Nextcloud or WebDAV in general.

**Comment by alexbakker** [comment] 2020-09-09 08:40
Duplicate of #258.

**Closed by alexbakker** 2020-09-09 08:40 UTC
Labels: proposal
