### ISSUE TITLE
Windows port of Aegis

### ISSUE THREAD

**Issue by PatRiot1337** [beemdevelopment/Aegis#979] opened 2022-09-04 21:15 UTC
May it be possible to build and compile a Windows port of Aegis with the functionality to import backups from the original Android version? That would be great. Even the FAQs say you don't have plans to port Aegis to other platforms, it would be an awesome feature and an unique selling point.

**Comment by alexbakker** [comment] 2022-09-05 19:19
Duplicate of #165.

**Closed by alexbakker** 2022-09-05 19:19 UTC
Labels: proposal
