### ISSUE TITLE
Unable to Read and Process QR code

### ISSUE THREAD

**Issue by zjagoo** [beemdevelopment/Aegis#124] opened 2019-06-02 17:23 UTC
Hello,
First of all, thank you for this excellent app. I have been using too many apps on my phone and this helped consolidate all of them into one single one. 
My phone camera has been having issues lately and I cannot use the QR code scanner. I am resorting to take a picture and try to scan the image. However, upon reading the image file, I get the error: 
Unable to Read and Process QR code
I am using the latest version (0.4.2) that was released a few days ago.
Does the app use an external software to do the decoding?
Thanks for taking the time to look into this.

**Comment by michaelschattgen** [comment] 2019-06-04 20:19
Hi Zjagoo, thanks for your report! We are glad to hear that you like our app.

It's working fine for me on 0.4.2. Could you send us the screenshot (with an invalid secret in it ofcourse!) so we can try to reproduce?

**Comment by alexbakker** [comment] 2019-09-07 19:49
I'm going to close this as we haven't gotten a response in the 3 months since this issue was created.

**Closed by alexbakker** 2019-09-07 19:49 UTC
