### ISSUE TITLE
Import from Clipboard

### ISSUE THREAD

**Issue by xmha97** [beemdevelopment/Aegis#1033] opened 2022-11-22 14:05 UTC
Please add feature below:
- Import from Clipboard
```
otpauth://totp/Bugzilla%3Axxxxxx%40gmail.com?secret=GFSDIT3COFMWEY3MNBDHQQRWMI&issuer=Bugzilla
```

**Comment by alexbakker** [comment] 2022-11-28 18:16
Duplicate of #950.

**Closed by alexbakker** 2022-11-28 18:16 UTC
Labels: proposal
