### ISSUE TITLE
Biometric authentication automatic popup for unlocking

### ISSUE THREAD

**Issue by MontblancKupo** [beemdevelopment/Aegis#581] opened 2020-08-30 21:23 UTC
Once biometric unlocking has been enabled, it would be really nice to have it automatically pop up as the default when opening the app. 

Right now you have to open the app, close your keyboard since it is the default and it covers the biometric option, then click the tiny biometric link, then it pops up the login prompt to touch your fingerprint reader. Most other apps will give you the option to use it by default and you'll simply be presented with a prompt the moment the app opens.

**Comment by michaelschattgen** [comment] 2020-08-30 21:25
This is a duplicate of #542. Entering your password once or disabling the password reminder will solve the issue for you.

**Closed by michaelschattgen** 2020-08-30 21:25 UTC
Labels: proposal
