### ISSUE TITLE
backup/export to Nextcloud folder failed

### ISSUE THREAD

**Issue by R1123345** [beemdevelopment/Aegis#615] opened 2020-11-24 11:30 UTC
Backup to nextcloud storage on the phone does not succeed. 

###### Info
Aegis 1.3 from F-Droid
Encrypted vault, biometrics enabled
Pixel 4 XL
Android 10, CalyxOS

###### Steps to reproduce
Option 1 - backup
1. Settings -> enable auto-backup
2. select nextcloud storage
3. select folder in nextcloud storage, 
4. allow access
5. wait for backup to trigger,or manually trigger a backup
6. error message displays

Option 2 - export
1. Settings -> export the vault
2. select nextcloud storage
3. select nextcloud folder 
4. hit "save"
5. error message displays
###### What do you expect to happen?

Backup/export should succeed

###### What happens instead?

Backup failed
Error: com.beemdevelopment.aegis.vault.vaultManagerException: createFile returned null

Export failed
Error: java.io.FileNotFoundException: Error downloading file: aegis-export-[yyyymmdd-[string]
A file of 0kb with the abovementioned name is created in the nextcloud folder.

**Comment by alexbakker** [comment] 2020-11-24 11:32
Duplicate of #610.

**Closed by alexbakker** 2020-11-24 11:32 UTC
Labels: bug
