### ISSUE TITLE
Option to automatically assign an icon based on Issuer?

### ISSUE THREAD

**Issue by beyond9thousand** [beemdevelopment/Aegis#1020] opened 2022-11-06 09:30 UTC
From what I've gathered so far, I must manually select each entry and assign the icons, which is a bit counter productive since the app is clearly able to provide available icons based on the text data (issuer name). Is there any way to automate this process? If not, can someone please implement this?

It just seems like a no brainer, but do tell me if there are some other mysterious reasons behind the lack of this functionality

**Comment by krisu5** [comment] 2022-11-06 10:56
Duplicate of #773

**Comment by beyond9thousand** [comment] 2022-11-06 11:16
I see, thank you for the input

**Closed** 2022-11-06 11:20 UTC
Labels: proposal
