### ISSUE TITLE
Multiple Devices Support and Cloud Sync 

### ISSUE THREAD

**Issue by yashbabani** [beemdevelopment/Aegis#721] opened 2021-04-13 11:14 UTC
Is there any planning to make an iOS App and the Chrome Extension in the near future?

iOS doesn't have that much amount of decent 2FA apps which are as good as Aegis

Also, is there any way to sync the codes between multiple devices and supports cloud backup i.e. Drive, Dropbox etc.?

**Comment by alexbakker** [comment] 2021-04-13 11:16
Duplicate of #290.

**Closed by alexbakker** 2021-04-13 11:16 UTC
