### ISSUE TITLE
No entries info not shown and entries missing

### ISSUE THREAD

**Issue by D3SOX** [beemdevelopment/Aegis#750] opened 2021-05-26 09:41 UTC
###### Info

* __Version__: 2.0
* __Source__: GitHub
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: OnePlus 8T
* __Android version and ROM__: 11, LineageOS 18.1-20210508-microG-kebab

###### Settings (if they are relevant)

* View mode: Compact
* Copy tokens when tapped: enabled
* Highlight tokens when tapped: disabled
* Delete vault on panic trigger: disabled
* Icon Pack: aegis-icons (v20210524)
* Encrypted + biometric unlock enabled
* Tap to reveal: enabled
* Auto lock: back button, device locked

###### Steps to reproduce

* Add some entries
* Tap the search icon
* Type some random letters so that no entries are shown
* (no "no entries found" warning now shown) (1)
* Tap the three dots icon
* Tap lock
* Tap on `biometrics` and unlock
* (now "no entries found" is there)
* Tap the X icon or remove the search text
* Still no entries found (2)

###### What do you expect to happen?

1. After typing something when it doesn't find an entry and it should show the "No entries found" info.
2. After unlocking again and removing the search text it should show the relevant entries.

###### What happens instead?

1. "No entries found" info not shown.
2. It still says that there were no entries found.

When restarting the app the entries are once again shown correctly.

###### Screen recording

(temporarily disabled show account names and screen security)

https://user-images.githubusercontent.com/24937357/119639422-e3c81d00-be17-11eb-8add-dc734a84223c.mp4

###### Log

```
--------- beginning of main
05-26 11:33:40.591 13537 13537 I AssistStructure: Flattened final assist data: 2640 bytes, containing 1 windows, 19 views
05-26 11:33:41.928 13537 13537 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
05-26 11:33:41.928 13537 13537 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
05-26 11:33:42.101 13537 14959 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.101 13537 14959 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.103 13537 14958 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.103 13537 14958 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.110 13537 14959 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.110 13537 14959 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.110 13537 14958 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:42.111 13537 14958 D skia    : --- Failed to create image decoder with message 'unimplemented'
05-26 11:33:45.733 13537 13537 I VaultBackupManager: Shutting down backup manager thread
05-26 11:33:45.866 13537 13537 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
05-26 11:33:48.000 13537 13537 I AssistStructure: Flattened final assist data: 3096 bytes, containing 1 windows, 21 views
```

**Comment by alexbakker** [comment] 2021-05-26 10:09
Thanks for the detailed bug report.

> After typing something when it doesn't find an entry and it should show the "No entries found" info.

This is not entirely unexpected behavior, but we should probably be more consistent about when we show the "No entries found" text.

> After unlocking again and removing the search text it should show the relevant entries.

Good catch! On a side note, it appears that this issue was also present in v1.4.2, so it's not something new in v2.0.

**Comment by D3SOX** [comment] 2021-05-26 10:38
> more consistent about when we show the "No entries found" text.

I think it should also be shown when you search for something and there are no results. Just like this but maybe with a different icon and with a different text

![image](https://user-images.githubusercontent.com/24937357/119645950-dd896f00-be1e-11eb-848f-6bef4d46b757.png)


> so it's not something new in v2.0.

Yeah, I could've noted that it's probably not specific to 2.0 because I was just playing around and discovered this.
Thanks for checking this anyways.

**Comment by Hacker437** [comment] 2021-11-07 09:15
@alexbakker I couldn't reproduce this bug, Once check and close the issue.

**Comment by alexbakker** [comment] 2021-11-07 17:57
You're right, this was fixed.

**Closed by alexbakker** 2021-11-07 17:57 UTC
Labels: bug, bug-confirmed
