### ISSUE TITLE
Progress bar should be in different color than warning text block

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#1268] opened 2024-01-23 03:01 UTC
![Screenshot_20240123_104307.jpg](https://github.com/beemdevelopment/Aegis/assets/1230959/61768b30-4c39-4d5c-a253-1c5dcc03d72e)

Here we see the progress bar is hard to see, because it is in the exact same color as the warning text block. Therefore the warning text should use a different color. Or the progress bar should use a different color.

You might say, "Well the user will dismiss the warning text shortly." But that's not always the case. Some users just live for ages with that same warning text.

Okay, maybe that bar isn't called the progress bar. But anyway I'm talking about the bar underneath that text block.

**Comment by alexbakker** [comment] 2024-01-23 06:53
Duplicate of #1049.

**Closed by alexbakker** 2024-01-23 06:53 UTC
