### ISSUE TITLE
Delay in OTP code change after expiration

### ISSUE THREAD

**Issue by 9mido** [beemdevelopment/Aegis#740] opened 2021-05-05 15:55 UTC
Sometimes the OTP code does not change right away after expiration to a new OTP code. Instead of getting a new OTP code as soon as the current OTP code expires, it keeps the old OTP code for about halfway through the expiration time of when the new OTP code should have been populated. With no delays, it would give people more time to enter the OTP code.

**Comment by alexbakker** [comment] 2021-05-05 17:15
Do you have a reproducible case or a demo of this happening?

**Comment by 9mido** [comment] 2021-05-05 18:02
The only thing I was doing was continuously logging into the same account form that uses an OTP stored on Aegis many times. It may have been caused by turning on/off the mobile device that has the Aegis app on it and then turning the mobile device that has the Aegis app back on again multiple times to see the OTP code again. Basically, it just happened after excessive use. Otherwise, I don't really have a reproducible case.

**Comment by alexbakker** [comment] 2021-05-06 21:48
In your testing, how are you determining that a code has expired? Is it by looking at the progress bar and it being fully depleted, but Aegis is not generating the next code yet? Or is a service rejecting a code you got from Aegis?

**Comment by 9mido** [comment] 2021-05-07 02:53
Yes the progress bar is being fully depleted and Aegis is not generating the next code yet. About 50-75% through the next available progress bar would it generate the new code.

It may have been from when I was testing it in my own app's form also. I was having problems with the entered OTP code and it was not being accepted. As soon as I re-did the OTP setup again on the mobile device and received a brand new OTP account for the website, everything went smooth and the OTP code was accepted. 

But it was really strange because sometimes the original code would be accepted but then sometimes it wouldn't. I was trying to use hcaptcha in the form but now it works after setting up a new account for Aegis. I transferred my app from 1 PC to another and used the original code which may have had something to do with causing it.

**Comment by alexbakker** [comment] 2022-12-26 12:12
I'm going to close this for now, since we're not able to reproduce this, and we have not received any other reports of this happening.

**Closed by alexbakker** 2022-12-26 12:12 UTC
Labels: bug
