### ISSUE TITLE
Aegis OTP Codes Not Working When Manually Transferred to Other OTP Clients

### ISSUE THREAD

**Issue by moderatedan** [beemdevelopment/Aegis#1508] opened 2024-10-02 08:17 UTC
### Version

"I prefer not to disclose detailed device information for privacy reasons, but I believe the issue is not device-specific."

### Source

Google Play

### Vault encryption

Yes

### Device

"I prefer not to disclose detailed device information for privacy reasons, but I believe the issue is not device-specific."

### Android version

"I prefer not to disclose detailed device information for privacy reasons, but I believe the issue is not device-specific."

### Steps to reproduce

Export an OTP secret from Aegis.
Manually enter the OTP secret into another OTP client.
Attempt to use the generated code for authentication on the relevant service.
The service rejects the OTP code generated by the new OTP client, though the Aegis-generated code works correctly.

### What do you expect to happen?

The manually transferred OTP secret should generate valid OTP codes in the new OTP client, matching the codes generated by Aegis.

### What happens instead?

The new OTP client generates OTP codes that are consistently rejected by the service, while the codes from Aegis continue to work correctly.

### Log

Note: The following section includes a detailed description of the issue and the steps already taken to troubleshoot.

Description:
I’ve encountered an issue when manually transferring OTP secrets from Aegis to another OTP client (e.g., Google Authenticator, Authy, etc.). After manually entering the secret, the generated OTP codes in the new client do not work with the associated service, despite confirming that all relevant factors have been properly configured. I have systematically verified that none of the usual issues are at play (details below).

Troubleshooting Steps Already Verified:
I have verified that the following potential causes are not the issue:

    Secret Key Accuracy: The secret key has been accurately transferred without any typographical errors.
    Time Synchronization: Both devices running Aegis and the new OTP client are time-synced to NTP servers, ensuring accurate time.
    OTP Type (TOTP vs HOTP): The correct OTP type (TOTP) has been selected, and I have verified that both Aegis and the new client use the same OTP type.
    Time Interval: Both Aegis and the new OTP client are set to the standard 30-second interval for generating new codes.
    Base Encoding (Base32 vs. Base64): The OTP secret key encoding format has been verified as correct (Base32) in both clients.
    Digit Length: Both Aegis and the new client are generating 6-digit OTP codes as required by the service.
    Service-Specific Requirements: I have reviewed the service’s OTP setup instructions and confirmed there are no unique requirements being overlooked.
    Manual Transfer Errors: The secret key has been carefully copied with attention to formatting, capitalization, and spacing to ensure consistency between both clients.

I would appreciate it if the team could investigate why OTP codes are not functioning correctly when transferred manually from Aegis to other OTP clients. If there are any known compatibility issues or additional steps required that I might have overlooked, please advise.

Thank you for your attention to this issue!

**Comment by michaelschattgen** [comment] 2024-10-02 10:31
Thanks for your report. I can't reproduce after trying with multiple entries and OTP apps. Are you sure you have completely copied over the secret? The textfield of the secret becomes horizontally scrollable when the secret is too long to show.

If that doesn't work either, could you try transferring the QR code through a screenshot (tap and hold the entry and tap the QR code at the top) and have the other OTP app scan that?

**Comment by michaelschattgen** [comment] 2024-10-14 06:27
Closing this due to no response.

**Closed** 2024-10-14 06:27 UTC
Labels: bug
