### ISSUE TITLE
Ability to choose a different password for a backup

### ISSUE THREAD

**Issue by Rendi-boi** [beemdevelopment/Aegis#557] opened 2020-08-08 07:35 UTC
Would it be possible to implement this feature like andOTP has? If user wants he could set a different password for a backup. This way user could use a bit shorter and easier to remember password for unlocking and everyday use (if he doesn't want to use biometrics), but much harder password would be fitting for backups to external storage.

**Comment by alexbakker** [comment] 2020-08-08 09:10
Yes. Duplicate of #121.

**Closed by alexbakker** 2020-08-08 09:10 UTC
Labels: proposal
