### ISSUE TITLE
Can't import the json file to Aegis Authenticator

### ISSUE THREAD

**Issue by Sarrieg** [beemdevelopment/Aegis#1442] opened 2024-08-01 19:28 UTC
Hi,
I exported the JSON file from an Aegis app and want to import it the app installed in another phone. I installed the Aegis app in the new phone without problems and locked it with a password (same as I did it in the old phone). When importing the JSON file I get "An error occurred when reading the file" and when clicking _More Details_ I get
"ImportFileTask(uri="file:///storage/emulated/0/Download/aegis-export-20210330-184013.json"): java.io.FileNotFoundException: /storage/emulated/0/Download/aegis-export-20210330-184013.json: open failed: EACCES (Permission denied)"

I installed the Aegis 3.1.1 version
Thank you in advance

**Comment by alexbakker** [comment] 2024-08-01 19:34
Duplicate of #1031.

**Closed by alexbakker** 2024-08-01 19:34 UTC

**Comment by Sarrieg** [comment] 2024-08-01 20:06
Thank you. Solved!!
