### ISSUE TITLE
Any plans for a cross-platform Desktop app?

### ISSUE THREAD

**Issue by damienbutt** [beemdevelopment/Aegis#1157] opened 2023-08-02 23:49 UTC
Currently using Authy as it's available on iOS and Android, and has desktop apps for Linux, macOS, and Windows.

It is not open source though.

I am looking at moving to Android so Aegis would be my preference but not having the desktop apps will be a real pain.

**Comment by alexbakker** [comment] 2023-08-03 11:39
Duplicate of #165.

**Closed by alexbakker** 2023-08-03 11:39 UTC
Labels: proposal
