### ISSUE TITLE
Trash folder and Archive folder

### ISSUE THREAD

**Issue by SujitPalRICO** [beemdevelopment/Aegis#1371] opened 2024-05-07 04:55 UTC
I think you should add a Trash folder and an Archive folder option. If we accidentally delete a token or if we change our mind after deleting a token or want to keep a token out of sight temporarily then we will be able get those back. I think these two features will be a very nice addition which will enrich the overall user experience and sets apart Aegis Authenticator from other authenticator apps out there. It will give users a peace of mind. I hope you will consider this. 
Thank you.

**Comment by michaelschattgen** [comment] 2024-05-07 11:26
We definitely should implement this, but it's a duplicate of #624.

**Closed by michaelschattgen** 2024-05-07 11:26 UTC
Labels: proposal
