### ISSUE TITLE
Letters in the account name filed displayed abnormally in the view mode of tiles

### ISSUE THREAD

**Issue by xdudna** [beemdevelopment/Aegis#1540] opened 2024-11-22 06:37 UTC
### Version

3.2

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Xiaomi mi 15

### Android version

Android 15

### Steps to reproduce

1. Set the view mode to tiles.
2. Make sure the option 'Show the account name' is enabled.
3. Check the entry whose name field contains letters 'y', 'j', 'g' ...

### What do you expect to happen?

the letters were shown completely.

### What happens instead?

when using the view mode of tiles, the lower portions of some letters in the name field were not completely shown. (e.g. letters like 'y', 'j', 'g' would be shown as 'v', 'i', handwritten 'a')

**Comment by alexbakker** [comment] 2024-11-22 16:55
Could you share a screenshot of what this looks like? (Temporarily disable "Screen security" in Aegis' setting first). Does it look similar to https://github.com/beemdevelopment/Aegis/issues/1477#issuecomment-2339959582?

**Comment by xdudna** [comment] 2024-11-22 18:26
![IMG_20241123_022603.jpg](https://github.com/user-attachments/assets/4bc3d446-17ee-48a1-908d-106ae7584cdb)

Yes, it's similar to that issue. 
BTW, I'm using the device's default font and default font size.

**Comment by alexbakker** [comment] 2024-11-23 11:50
Thanks, closing this as a duplicate of #1477.

**Closed by alexbakker** 2024-11-23 11:50 UTC
Labels: bug
