### ISSUE TITLE
Add support for encrypting backups with a public key.

### ISSUE THREAD

**Issue by Crowley723** [beemdevelopment/Aegis#1289] opened 2024-02-29 21:53 UTC
I just switched to Aegis from Google authenticator and noticed that there doesn't seem to be a way I can do automatic backups with my own keypair. 

Ideally the app would allow me to input my public key either gpg or ssh, and when an automatic backup is performed the backup is encrypted using the public key before it is stored on disk or in the cloud.

This would give people with hardware keys with stored gpg keys the ability to take control over the encryption of their backups.

Currently I export the backup as plain json then use openkeychain to encrypt the json file. Great for manual backups but not so much for automatic.

**Comment by alexbakker** [comment] 2024-03-01 11:18
Duplicate of #614. We don't have plans to implement support for this.

**Closed by alexbakker** 2024-03-01 11:18 UTC
Labels: proposal
