### ISSUE TITLE
Browser Extension to receive codes in clipboard

### ISSUE THREAD

**Issue by blurayne** [beemdevelopment/Aegis#684] opened 2021-02-07 18:22 UTC
Seen on other authenticators.

Chrome/Firefox Extension

1. Tap copy on shown code in app 
2. Browser Extension receives code 
3. Code is copied to clipboard
4. Or better: website is remembered and extension knows where to paste the code and clicks submit (maybe default set? Maybe let user add via spath)

**Comment by alexbakker** [comment] 2021-02-07 19:02
Duplicate of #674.

**Closed by alexbakker** 2021-02-07 19:02 UTC
Labels: proposal
