### ISSUE TITLE
Is there any chance to consider maintaining the Windows version of 2-FA TOTP app, like WinAuth?

### ISSUE THREAD

**Issue by ttodua** [beemdevelopment/Aegis#846] opened 2021-11-06 11:36 UTC
A couple years ago, an excellent windows app [WinAuth](https://github.com/winauth/winauth) has been under an active development. However, the author has stopped development eventually. Now, several years has passed, and there is still no REALISTIC 2-FA TOTP app for Windows users with similar development. However, alike your Aegis app (which is the exceptionally top-notch totp app I've ever came across for android) the WinAuth lacked many features (search, auto-copy, QR-code drag & drop and many others), which I've forked, added those features and published [a new repository](https://github.com/ttodua/winauth).  I think, that there are quite large audience of Windows users, who need to have TOPT 2-FA app on pc (instead of having a constant dependency on mobile device). My fork and updates gain some bit attraction and it seems the most-developed & forked one from all the forks, as seen [here](https://github.com/winauth/winauth/network/members) and [here](https://techgaun.github.io/active-forks/#winauth/winauth).

So, what I wanted to say - I think it will be a quite good if you took over that GPL 3.0 project, and thus, having a supported & popular 2-FA app for Windows, might be useful for community, if you will have any will to do so, and I will happily redirect my repository & followers to yours. (and maybe name it `WinAuth by Aegis`)

**Comment by Hacker437** [comment] 2021-11-06 14:29
Duplicate of #165.

**Comment by alexbakker** [comment] 2021-11-07 17:49
Taking over another project and changing it to our standards would probably take longer than just starting over. But as said before, we don't have plans to port Aegis to other platforms.

**Closed by alexbakker** 2021-11-07 17:49 UTC
Labels: proposal
