### ISSUE TITLE
Color warning when code is closed to be expired

### ISSUE THREAD

**Issue by o101010** [beemdevelopment/Aegis#1353] opened 2024-04-14 19:13 UTC
Hi,

Thank you for the amazing job on this app.

What do you think about having the OTP code color changing when it's being close to expire ?
It's so a frustration when you enter your OTP code in your login page and get an error because it has already changed.

It was a cool feature present on the deadly andOTP.

<img src="https://github.com/beemdevelopment/Aegis/assets/23003062/b4ed20bb-b769-4821-a543-2130d8bac0c1" width="250" >
<img src="https://github.com/beemdevelopment/Aegis/assets/23003062/6ab9a998-773e-462b-980b-ebc7ef2800d9" width="250" >

[edit] : change screenshot sizes

**Comment by michaelschattgen** [comment] 2024-04-15 10:07
Duplicate of #411.

**Closed by michaelschattgen** 2024-04-15 10:07 UTC
Labels: proposal
