### ISSUE TITLE
Add an option to show uncropped icons

### ISSUE THREAD

**Issue by sabi0** [beemdevelopment/Aegis#1118] opened 2023-04-03 12:04 UTC
Not every icon / logo looks nice cropped to a circle.
Take for instance Microsoft logo:
![image](https://user-images.githubusercontent.com/11509875/229502858-5d9a569b-1c6e-46db-ba0b-053764cf7cba.png)

The icon looks nicer in the (legacy) FreeOTP:
![image](https://user-images.githubusercontent.com/11509875/229502939-16e221cf-7f10-43e7-abb2-0178df08a75a.png)

I would love to have full control over how the entries' icons are displayed.

**Comment by alexbakker** [comment] 2023-04-11 20:04
Duplicate of #216.

**Closed as not planned by alexbakker** 2023-04-11 20:04 UTC
Labels: proposal
