### ISSUE TITLE
Hidden token codes placeholder characters is wider then revealed code number which breaks layout so it takes more vertical space than it could

### ISSUE THREAD

**Issue by Mr-KoKa** [beemdevelopment/Aegis#1453] opened 2024-08-09 21:16 UTC
### Version

3.1.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung Galaxy S8

### Android version

Android 9

### Steps to reproduce

My guess the issue occurs because of my screen ratio.
My phone settings allows me to set these resolutions 1480x720 2220x1080 2960x1440

### What do you expect to happen?
(I covered my token names with grey rectangle, it is not a bug)

Any of the following would be alright, even empty tile.
![image](https://github.com/user-attachments/assets/175bc9ca-90da-4618-801c-19292ef33a90)

### What happens instead?
(I covered my token names with grey rectangle, it is not a bug)

Hidden token code character is wider than numbers and layout breaks so instead having many more token visible in compact layout, only so many tokens are visible on single page.
![image](https://github.com/user-attachments/assets/65156faa-957c-416d-ac63-03e13a30a565)

**Comment by michaelschattgen** [comment] 2024-08-09 21:20
Duplicate of #1012. Unfortunately we haven't come up with a good solution yet.

**Closed by michaelschattgen** 2024-08-09 21:20 UTC
Labels: bug
