### ISSUE TITLE
Add Yubikey support

### ISSUE THREAD

**Issue by Ortovoxx** [beemdevelopment/Aegis#1070] opened 2022-12-26 13:16 UTC
I would love to see Yubikey support in 2 ways:

1. As an extra level of authentication when decrypting the vault alongside biometrics/password to allow for MFA to those accounts that only use 2FA.

2. Working as the actual secret store as seen in yubicos very own [authenticator app](https://play.google.com/store/apps/details?id=com.yubico.yubioath)

Yubico have some [developer docs](https://developers.yubico.com/)

Let me know your thoughts

**Comment by alexbakker** [comment] 2022-12-26 13:21
Duplicate of #336 and #1021.

**Closed by alexbakker** 2022-12-26 13:21 UTC
Labels: proposal
