### ISSUE TITLE
Some source texts displayed in the interface missing from the localisation platform supposed to host them

### ISSUE THREAD

**Issue by Ricky-Tigg** [beemdevelopment/Aegis#1448] opened 2024-08-06 18:20 UTC
### Version

3.1.1

### Source

Google Play

### Vault encryption

No

### Device

Android

### Android version

any

### Steps to reproduce

Hello. Some texts displayed in the interface of this application in their source language are missing from the localisation platform that this project has chosen. This is the case, among others, of "_This is a very common password._" [here](https://crowdin.com/project/aegis-authenticator/fi#/master), in the **strings.xml** file, which is the only resource accessible to the holder of a translator account. Same observation regarding this repository in the "_main_" branch, in `app/src/main/res/values/strings.xml`. What could be the origin of these texts, in order to translate them?

### What do you expect to happen?

_

### What happens instead?

_

**Comment by alexbakker** [comment] 2024-08-07 16:49
Duplicate of #1209.

**Closed by alexbakker** 2024-08-07 16:49 UTC
Labels: bug
