### ISSUE TITLE
Unable to read and process QR code from Google auth export

### ISSUE THREAD

**Issue by janumiko** [beemdevelopment/Aegis#1292] opened 2024-03-09 21:09 UTC
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Samsung A52s 5G

### Android version

Android 14

### ROM

Original from Samsung

### Steps to reproduce

1. Enter into Google Authenticator
2. Click transfer account and export accounts, which shows 2 QR codes (in my case).
3. Screenshot the 1st and 2nd QR code (trim image to contain only QR code).
4. Enter into Aegis and scan the screenshots of QR codes from above.

### What do you expect to happen?

Import codes into the Aegis app.

### What happens instead?

The Second QR code works, but shows the warning about a partial import from Google Authenticator.
But the first QR code causes an error:
"Unable to read and process QR code from file: <filename>"
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError:com.google.zxing.NotFoundException

Tried to screenshot the QR code in different ways, but it doesn't work.
I don't think the screenshot matters because the 2nd QR code is imported correctly.

I have over 20 codes in Google Auth. 
Google auth version is 6.0
Aegis version is 2.2.2

When I export codes one by one it works. So I guess the error is caused when multiple codes are exported at once into one image (the default behaviour of google auth)

**Comment by alexbakker** [comment] 2024-03-10 10:11
Duplicate of #1185.

**Closed by alexbakker** 2024-03-10 10:11 UTC
Labels: bug
