### ISSUE TITLE
Settings don't get imported

### ISSUE THREAD

**Issue by ghost** [beemdevelopment/Aegis#1547] opened 2024-11-25 13:22 UTC
### Version

3.3

### Source

GitHub

### Vault encryption

Yes (with biometric unlock)

### Device

Xiaomi Poco X3 NFC

### Android version

Android 14

### ROM

LineageOS

### Steps to reproduce

1. Import Aegis JSON
2. Need to change the Settings manually

### What do you expect to happen?

That all my Settings get imported too, that I don't need to change them always manually, because it is time and energy consuming to always change them after importing.

### What happens instead?

I need to change all Settings manually, even tho I imported the JSON.

**Comment by michaelschattgen** [comment] 2024-11-25 13:58
Duplicate of #944.

**Closed as not planned by michaelschattgen** 2024-11-25 13:58 UTC
Labels: bug
