### ISSUE TITLE
Make a Desktop App

### ISSUE THREAD

**Issue by shashank-brdj** [beemdevelopment/Aegis#675] opened 2021-01-24 19:22 UTC
Greetings team!
Amazing app with great features. I recently shifted from Authy to this, and man should I say I'm way more than impressed?
Option to manually backup the keys encrypted, add custom icons, screenshot proofing feature, option to generate QR codes and easily store them in case of last resort is wonderful. I literally have no regrets joining Aegis Fanbase. Great work!!
That said, the only feature which I miss from Authy is desktop app. I want to be able to use aegis on my pc incase my I don't have my phone on me. Can you please try to make a pc app? it would be amazing and super easy to use. It's ok if it's just like phone app, cloud sync and device sync is not a must. Cuz using a VM to use this on pc is a bit of overkill and tedious don't you think?
Give it a thought :D
Thanks a ton!!

**Comment by alexbakker** [comment] 2021-01-24 19:23
Thanks for the kind words, but this is a duplicate of #165.

**Closed by alexbakker** 2021-01-24 19:23 UTC
Labels: proposal
