### ISSUE TITLE
Show biometric unlock by default when biometric authentication is enabled

### ISSUE THREAD

**Issue by theRealPadster** [beemdevelopment/Aegis#590] opened 2020-09-21 00:17 UTC
When I open Aegis, it defaults to typing a password, which brings my keyboard up. I can't scroll the page and need to collapse my keyboard and tap "use biometrics" in order to authenticate. 

Most other apps that use biometrics just pop up the biometric dialog when they open up, which is much more user-friendly. 

![Screenshot_20200920-201101](https://user-images.githubusercontent.com/1565883/93725567-488ef180-fb7e-11ea-9ffd-aa44391ad764.png)
![Screenshot_20200920-201110](https://user-images.githubusercontent.com/1565883/93725568-49c01e80-fb7e-11ea-9874-e9ad4cf07b82.png)

**Comment by alexbakker** [comment] 2020-09-21 15:16
Duplicate of #542.

**Closed by alexbakker** 2020-09-21 15:16 UTC
Labels: proposal
