### ISSUE TITLE
Codes Auto-Copying To Clipboard On FIRST Tap

### ISSUE THREAD

**Issue by Vasd-Q** [beemdevelopment/Aegis#317] opened 2020-02-18 03:36 UTC
###### Info

* __Version__: 1.1.4
* __Source__: F-Droid
* __Vault encrypted:__ Yes (without biometric unlock)
* __Device:__ Samsung Galaxy S10
* __Android version and ROM:__ Android 10

###### Steps to reproduce

Go to app settings and enable "Tap to reveal".
Tap any of your accounts to reveal the code.
The code is now automatically copied to your clipboard even if you just wanted to view the code.

###### What do you expect to happen?

I believe after the latest update, or the one before the latest, this started happening.
Before updating I had to tap TWICE to copy the code (if using "Tap to reveal"), this was way better in my opinion because I didn't have to spam my clipboard with unnecessary data if I'm going to enter the code on a desktop PC.

###### What happens instead?

When tapping your account name to reveal the code, it is copied to your clipboard.

###### Log

N/A

**Comment by alexbakker** [comment] 2020-02-18 17:31
Duplicate of #280.

**Closed by alexbakker** 2020-02-18 17:31 UTC
Labels: bug
