### ISSUE TITLE
Backup  and Sync with Google Drive

### ISSUE THREAD

**Issue by xxvincixx** [beemdevelopment/Aegis#882] opened 2022-02-04 21:04 UTC
hello, is it possible to add the ability to backup on G drive so you can have everything synchronized on multiple devices ?? thanks

**Comment by alexbakker** [comment] 2022-02-04 21:12
Duplicate of #866.

**Closed by alexbakker** 2022-02-04 21:12 UTC
Labels: proposal

**Comment by xxvincixx** [comment] 2022-02-04 21:14
oh sorry...
