### ISSUE TITLE
add option to encrypt only auto-backups

### ISSUE THREAD

**Issue by ossilator** [beemdevelopment/Aegis#1575] opened 2024-12-15 14:32 UTC
as an extension to #121 and #512:

if one consider the device "sufficiently secure", then only backed up data needs encrypting. this is already implemented for manual backups, but i would want to do that for auto-backups, so stuff gets securely syncthing'd without manual intervention.

that means that the option to set a separate password for backups need to be available regardless of vault encryption, and auto-backup availability needs to be conditional on either being set. though i would probably re-organize things and put the backup pw setup onto the backup screen itself.

if android (cloud) backup can be configured at file-level granularity, then implementing the above would also enable secure cloud backups of unencrypted vaults.

**Comment by alexbakker** [comment] 2024-12-20 11:04
Duplicate of #1345.

**Closed by alexbakker** 2024-12-20 11:04 UTC
Labels: proposal

**Comment by ossilator** [comment] 2024-12-20 11:18
damn, i have a talent for picking the wrong search terms. :innocent:
