### ISSUE TITLE
Don't duplicate entries upon import

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#951] opened 2022-07-31 18:29 UTC
Users often sync different instances of Aegis via export and import.
Let's say he has 14 entries, only two of which are new.

Well, importing on a device with 12 entries should result in 14 entries, not 26, 12 of which are doubles.

**Comment by jidanni** [comment] 2022-07-31 18:31
Yes, you could say he should have been more careful when checking the checkboxes. But doubled entries never make sense in the first place.

**Comment by alexbakker** [comment] 2022-08-02 20:09
Duplicate of #453.

**Closed by alexbakker** 2022-08-02 20:09 UTC
