### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by GeorgGa** [beemdevelopment/Aegis#313] opened 2020-02-16 20:37 UTC
Is there even a need for a Windows version of Aegis at all for Windows-based 3G tablets for example and if so, is there any plan on adding a version for Windows?
Would highly appreciate it.
Thanks for all

**Comment by alexbakker** [comment] 2020-02-17 13:28
Duplicate of #165

**Closed by alexbakker** 2020-02-17 13:28 UTC
Labels: proposal
