### ISSUE TITLE
Importing QR from google authenticator error (multiple image)

### ISSUE THREAD

**Issue by dhana-exe** [beemdevelopment/Aegis#1290] opened 2024-03-06 12:07 UTC
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Redmi 10

### Android version

13

### ROM

Miui 14

### Steps to reproduce

-- Having 19 OTP on google authenticator
1. click transfer account
2. Since maybe 1 qr only handle 10 OTP account so they give us 2 picture... we call it PICTURE ONE and PICTURE TWO
3. when we scan the PICTURE ONE the app working great... but when we comes to second ones it somehow not works

it can be also tested with
1. click transfer account on gauth
2. save 2 picture like we did before
3. scan on aegis but this ones scan booth of it..... it will not works

all the apps said is
Screenshot_2024-03-06-18-54-02-605_com.google.android.apps.authenticator2.jpg:
com.beemdevelopment.aegis.helpers.QrCodeHelper$DecodeError: com.google.zxing.NotFoundException

### What do you expect to happen?

ofc working like what it did on first picture

### What happens instead?

error

### Log

dunno what was that

**Comment by alexbakker** [comment] 2024-03-08 16:49
Duplicate of #1185.

**Closed by alexbakker** 2024-03-08 16:49 UTC
Labels: bug
