### ISSUE TITLE
Auto-fill service not working anymore after updating to GrapheneOS Amdroid 13

### ISSUE THREAD

**Issue by ghost** [beemdevelopment/Aegis#977] opened 2022-09-02 06:23 UTC
###### Info

* __Version__: 2.0.3
* __Source__: (Google Play/GitHub/F-Droid/?) Google Play
* __Vault encrypted__: Yes (with biometric unlock)/Yes with password
* __Device__: Pixel 4a 5G
* __Android version and ROM__: 13, GrapheneOS

###### Steps to reproduce

I use keepass2android as my password manager and have it enabled as my auto-fill service. On GrapheneOS Android 12 I used the auto-fill service to log into the Aegis app since this was encrypted with a password. Since updating to GrapheneOS Android 13:
- open Aegis
- long press password field for auto-fill option to show
- choose auto-fill option
- "contents can't be auto-filled" message pops up

This also happens when Google is selected as the auto-fill service. This issue is not present in all apps.

###### What do you expect to happen?

On opening the Aegis app, immediately see the password option in the auto-fill dropdown menu which is suggested by the auto-fill service.

###### What happens instead?

No suggestion and error message when manually trying to start auto-fill service

**Comment by alexbakker** [comment] 2022-09-13 19:51
Are you able to reproduce this on vanilla Android 13? I don't currently have a device with GrapheneOS to test with and I'm not able to reproduce this.

**Comment by betweenwater** [comment] 2022-09-15 08:12
Thanks, and I appreciate that you can't test it, unfortunately I don't have a vanilla Android 13 myself. Although I did switch password manager to KeePassDX which is working with Aegis so perhaps it is more related with the previous password manager? A number of issue reports there too.

**Comment by alexbakker** [comment] 2024-09-11 07:57
Since we have not received any other reports of this, I'll close this for now.

**Closed by alexbakker** 2024-09-11 07:57 UTC
Labels: bug
